//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProcedureCallResult.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Collections.Generic;

namespace SFX.DAL.Helpers
{
    public sealed class ProcedureCallResult<T>
    {
        public List<T> Rows { get; set; } = new List<T>();
        public IReadOnlyDictionary<string, object?> OutputParameters { get; set; } = new Dictionary<string, object?>();

        public object? this[string outputParameterName] => OutputParameters.TryGetValue(outputParameterName, out object? value) ? value : null;
    }
}
