//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadDefinitionBody.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisReadDefinitionBodyRepository
    {
        ProcedureCallResult<AnalysisReadDefinitionBody> Execute(string objectKind, string declaredId, long? estateModelPk = null, string? path = null, int? topN = null, int? maxDepth = null);
        Task<ProcedureCallResult<AnalysisReadDefinitionBody>> ExecuteAsync(string objectKind, string declaredId, long? estateModelPk = null, string? path = null, int? topN = null, int? maxDepth = null);
    }
}
