//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadLiveScenarioCircuit.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisReadLiveScenarioCircuitRepository
    {
        ProcedureCallResult<AnalysisReadLiveScenarioCircuit> Execute(string input, long estateModelPk, bool? emit = null);
        Task<ProcedureCallResult<AnalysisReadLiveScenarioCircuit>> ExecuteAsync(string input, long estateModelPk, bool? emit = null);
    }
}
