//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadCapabilityInspection.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisReadCapabilityInspectionRepository
    {
        ProcedureCallResult<object?> Execute(string capabilityId, long estateModelPk);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, long estateModelPk);
    }
}
