//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelAddExample.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelAddExampleRepository
    {
        ProcedureCallResult<ModelAddExample> Execute(string capabilityId, string fixtureId, string inputJson, string expectedJson, string fixtureProfile);
        Task<ProcedureCallResult<ModelAddExample>> ExecuteAsync(string capabilityId, string fixtureId, string inputJson, string expectedJson, string fixtureProfile);
    }
}
