//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelAddProvider.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelAddProviderRepository
    {
        ProcedureCallResult<object?> Execute(string providerId, string name, string capabilitiesJson, string operationsJson, string configurationJson, string onExists);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string providerId, string name, string capabilitiesJson, string operationsJson, string configurationJson, string onExists);
    }
}
