//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelRemovePortProviderReference.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelRemovePortProviderReferenceRepository
    {
        ProcedureCallResult<object?> Execute(long portVersionPk, string expectedDefinitionDigest);
        Task<ProcedureCallResult<object?>> ExecuteAsync(long portVersionPk, string expectedDefinitionDigest);
    }
}
