//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelScaffoldCapability.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelScaffoldCapabilityRepository
    {
        ProcedureCallResult<object?> Execute(string capabilityId, string greetingTemplate, string inputId, string inputContract, string outcomeId, string outcomeContract, string onExists);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, string greetingTemplate, string inputId, string inputContract, string outcomeId, string outcomeContract, string onExists);
    }
}
