//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelUpdateDefinitionValue.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelUpdateDefinitionValueRepository
    {
        ProcedureCallResult<object?> Execute(string id, string pathSuffix, string value, string @namespace);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string id, string pathSuffix, string value, string @namespace);
    }
}
