//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelReviseTransformation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelReviseTransformationRepository
    {
        ProcedureCallResult<object?> Execute(string @namespace, string id, string expressionJson, string expectedDigest);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string @namespace, string id, string expressionJson, string expectedDigest);
    }
}
