//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelRenameDefinitionLabel.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelRenameDefinitionLabelRepository
    {
        ProcedureCallResult<object?> Execute(string @namespace, string declaredId, string label);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string @namespace, string declaredId, string label);
    }
}
