//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelScaffoldComposedCapability.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelScaffoldComposedCapabilityRepository
    {
        ProcedureCallResult<object?> Execute(string capabilityId, string inputContract, string inputSchema, string outcomeContract, string outcomeSchema, string targets, string description, string onExists);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, string inputContract, string inputSchema, string outcomeContract, string outcomeSchema, string targets, string description, string onExists);
    }
}
