//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareProviderSlot.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;

namespace SFX.DAL.Interfaces
{
    public partial interface IModelDeclareProviderSlotRepository
    {
        ProcedureCallResult<object?> Execute(string capabilityId, string slotId, string? providerProfile = null, long? expectedBlueprintVersionPk = null);
        Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, string slotId, string? providerProfile = null, long? expectedBlueprintVersionPk = null);
    }
}
