//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'IdentityBeginAuthenticationAttempt.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.Identity.DAL.Models
{
    public partial class IdentityBeginAuthenticationAttempt
    {
        public Guid? AttemptId { get; set; }
        public DateTimeOffset? ExpiresAt { get; set; }
        public bool? Allowed { get; set; }
    }
}