//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Authority.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class AuthorityRepository : IAuthorityRepository
    {
        private readonly string _connectionString;

        public AuthorityRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(Authority entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[authority] ([authority_id], [namespace_pk], [object_kind], [semantic_object_pk]) VALUES (@AuthorityId, @NamespacePk, @ObjectKind, @SemanticObjectPk); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToAuthorityParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(Authority entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[authority] SET
 [authority_id] = @AuthorityId, [namespace_pk] = @NamespacePk, [object_kind] = @ObjectKind, [semantic_object_pk] = @SemanticObjectPk WHERE [authority_pk] = @AuthorityPk", connection))
                {
                    connection.Open();

                    MapValuesToAuthorityParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(Authority entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[authority] WHERE [authority_pk] = @AuthorityPk", connection))
                {
                    command.Parameters.AddWithValue("@AuthorityPk", entity.AuthorityPk);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<Authority?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [authority_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToAuthorityAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<Authority>> GetAllAsync()
        {
            var entities = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<Authority>> GetAnyAsync(QueryDetail<Authority> queryDetail)
        {
            var entities = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<Authority>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<Authority>> GetByAuthorityIdAsync(string id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [authority_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Authority>> GetByNamespacePkAsync(long id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [namespace_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Authority>> GetByObjectKindAsync(string id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Authority>> GetBySemanticObjectPkAsync(long id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToAuthorityAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<Authority> MapReaderToAuthorityAsync(SqlDataReader reader)
        {
            return new Authority
            {
                AuthorityId = reader.GetString(reader.GetOrdinal("authority_id")),
                AuthorityPk = reader.GetInt64(reader.GetOrdinal("authority_pk")),
                NamespacePk = reader.GetInt64(reader.GetOrdinal("namespace_pk")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk"))
            };
        }
        
        public object Add(Authority entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[authority] ([authority_id], [namespace_pk], [object_kind], [semantic_object_pk]) VALUES (@AuthorityId, @NamespacePk, @ObjectKind, @SemanticObjectPk); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToAuthorityParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(Authority entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[authority] SET
 [authority_id] = @AuthorityId, [namespace_pk] = @NamespacePk, [object_kind] = @ObjectKind, [semantic_object_pk] = @SemanticObjectPk WHERE [authority_pk] = @AuthorityPk", connection))
                {
                    connection.Open();

                    MapValuesToAuthorityParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(Authority entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[authority] WHERE [authority_pk] = @AuthorityPk", connection))
                {
                    command.Parameters.AddWithValue("@AuthorityPk", entity.AuthorityPk);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public Authority? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [authority_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToAuthority(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<Authority> GetAll()
        {
            var entities = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<Authority> GetAny(QueryDetail<Authority> queryDetail)
        {
            var entities = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<Authority>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<Authority> GetByAuthorityId(string id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [authority_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Authority> GetByNamespacePk(long id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [namespace_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Authority> GetByObjectKind(string id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Authority> GetBySemanticObjectPk(long id)
        {
            List<Authority> results = new List<Authority>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[authority]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToAuthority(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public Authority MapReaderToAuthority(SqlDataReader reader)
        {
            return new Authority
            {
                AuthorityId = reader.GetString(reader.GetOrdinal("authority_id")),
                AuthorityPk = reader.GetInt64(reader.GetOrdinal("authority_pk")),
                NamespacePk = reader.GetInt64(reader.GetOrdinal("namespace_pk")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "AuthorityId", "authority_id" },
            { "AuthorityPk", "authority_pk" },
            { "NamespacePk", "namespace_pk" },
            { "ObjectKind", "object_kind" },
            { "SemanticObjectPk", "semantic_object_pk" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<Authority> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<Authority>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<Authority>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY authority_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [model].[authority]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToAuthorityParameters(SqlCommand command, Authority entity)
        {
            command.Parameters.AddWithValue("@AuthorityId", entity.AuthorityId);
            command.Parameters.AddWithValue("@AuthorityPk", entity.AuthorityPk);
            command.Parameters.AddWithValue("@NamespacePk", entity.NamespacePk);
            command.Parameters.AddWithValue("@ObjectKind", entity.ObjectKind);
            command.Parameters.AddWithValue("@SemanticObjectPk", entity.SemanticObjectPk);
        }
        
    }
}

