//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'BlueprintBoundedReturn.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class BlueprintBoundedReturnRepository : IBlueprintBoundedReturnRepository
    {
        private readonly string _connectionString;

        public BlueprintBoundedReturnRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(BlueprintBoundedReturn entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[blueprint_bounded_return] ([_canonical_pointer], [_owner_definition_pk], [authority_definition_pk], [blueprint_edge_pk], [declared_bound_content_pk], [return_kind]) VALUES (@CanonicalPointer, @OwnerDefinitionPk, @AuthorityDefinitionPk, @BlueprintEdgePk, @DeclaredBoundContentPk, @ReturnKind); SELECT @BlueprintEdgePk;", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToBlueprintBoundedReturnParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(BlueprintBoundedReturn entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[blueprint_bounded_return] SET
 [_canonical_pointer] = @CanonicalPointer, [_owner_definition_pk] = @OwnerDefinitionPk, [authority_definition_pk] = @AuthorityDefinitionPk, [declared_bound_content_pk] = @DeclaredBoundContentPk, [return_kind] = @ReturnKind WHERE [blueprint_edge_pk] = @BlueprintEdgePk", connection))
                {
                    connection.Open();

                    MapValuesToBlueprintBoundedReturnParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(BlueprintBoundedReturn entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[blueprint_bounded_return] WHERE [blueprint_edge_pk] = @BlueprintEdgePk", connection))
                {
                    command.Parameters.AddWithValue("@BlueprintEdgePk", entity.BlueprintEdgePk);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<BlueprintBoundedReturn?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [blueprint_edge_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToBlueprintBoundedReturnAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<BlueprintBoundedReturn>> GetAllAsync()
        {
            var entities = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<BlueprintBoundedReturn>> GetAnyAsync(QueryDetail<BlueprintBoundedReturn> queryDetail)
        {
            var entities = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<BlueprintBoundedReturn>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<BlueprintBoundedReturn>> GetByOwnerDefinitionPkAsync(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [_owner_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<BlueprintBoundedReturn>> GetByAuthorityDefinitionPkAsync(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [authority_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<BlueprintBoundedReturn>> GetByBlueprintEdgePkAsync(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [blueprint_edge_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<BlueprintBoundedReturn>> GetByDeclaredBoundContentPkAsync(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [declared_bound_content_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToBlueprintBoundedReturnAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<BlueprintBoundedReturn> MapReaderToBlueprintBoundedReturnAsync(SqlDataReader reader)
        {
            return new BlueprintBoundedReturn
            {
                CanonicalPointer = reader.GetString(reader.GetOrdinal("_canonical_pointer")),
                CanonicalPointerKey = await reader.IsDBNullAsync(reader.GetOrdinal("_canonical_pointer_key")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("_canonical_pointer_key")),
                OwnerDefinitionPk = reader.GetInt64(reader.GetOrdinal("_owner_definition_pk")),
                AuthorityDefinitionPk = reader.GetInt64(reader.GetOrdinal("authority_definition_pk")),
                BlueprintEdgePk = reader.GetInt64(reader.GetOrdinal("blueprint_edge_pk")),
                DeclaredBoundContentPk = reader.GetInt64(reader.GetOrdinal("declared_bound_content_pk")),
                ReturnKind = reader.GetString(reader.GetOrdinal("return_kind"))
            };
        }
        
        public object Add(BlueprintBoundedReturn entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[blueprint_bounded_return] ([_canonical_pointer], [_owner_definition_pk], [authority_definition_pk], [blueprint_edge_pk], [declared_bound_content_pk], [return_kind]) VALUES (@CanonicalPointer, @OwnerDefinitionPk, @AuthorityDefinitionPk, @BlueprintEdgePk, @DeclaredBoundContentPk, @ReturnKind); SELECT @BlueprintEdgePk;", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToBlueprintBoundedReturnParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(BlueprintBoundedReturn entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[blueprint_bounded_return] SET
 [_canonical_pointer] = @CanonicalPointer, [_owner_definition_pk] = @OwnerDefinitionPk, [authority_definition_pk] = @AuthorityDefinitionPk, [declared_bound_content_pk] = @DeclaredBoundContentPk, [return_kind] = @ReturnKind WHERE [blueprint_edge_pk] = @BlueprintEdgePk", connection))
                {
                    connection.Open();

                    MapValuesToBlueprintBoundedReturnParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(BlueprintBoundedReturn entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[blueprint_bounded_return] WHERE [blueprint_edge_pk] = @BlueprintEdgePk", connection))
                {
                    command.Parameters.AddWithValue("@BlueprintEdgePk", entity.BlueprintEdgePk);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public BlueprintBoundedReturn? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [blueprint_edge_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToBlueprintBoundedReturn(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<BlueprintBoundedReturn> GetAll()
        {
            var entities = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<BlueprintBoundedReturn> GetAny(QueryDetail<BlueprintBoundedReturn> queryDetail)
        {
            var entities = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<BlueprintBoundedReturn>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<BlueprintBoundedReturn> GetByOwnerDefinitionPk(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [_owner_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<BlueprintBoundedReturn> GetByAuthorityDefinitionPk(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [authority_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<BlueprintBoundedReturn> GetByBlueprintEdgePk(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [blueprint_edge_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<BlueprintBoundedReturn> GetByDeclaredBoundContentPk(long id)
        {
            List<BlueprintBoundedReturn> results = new List<BlueprintBoundedReturn>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[blueprint_bounded_return]   WHERE [declared_bound_content_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToBlueprintBoundedReturn(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public BlueprintBoundedReturn MapReaderToBlueprintBoundedReturn(SqlDataReader reader)
        {
            return new BlueprintBoundedReturn
            {
                CanonicalPointer = reader.GetString(reader.GetOrdinal("_canonical_pointer")),
                CanonicalPointerKey = reader.IsDBNull(reader.GetOrdinal("_canonical_pointer_key")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("_canonical_pointer_key")),
                OwnerDefinitionPk = reader.GetInt64(reader.GetOrdinal("_owner_definition_pk")),
                AuthorityDefinitionPk = reader.GetInt64(reader.GetOrdinal("authority_definition_pk")),
                BlueprintEdgePk = reader.GetInt64(reader.GetOrdinal("blueprint_edge_pk")),
                DeclaredBoundContentPk = reader.GetInt64(reader.GetOrdinal("declared_bound_content_pk")),
                ReturnKind = reader.GetString(reader.GetOrdinal("return_kind"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CanonicalPointer", "_canonical_pointer" },
            { "CanonicalPointerKey", "_canonical_pointer_key" },
            { "OwnerDefinitionPk", "_owner_definition_pk" },
            { "AuthorityDefinitionPk", "authority_definition_pk" },
            { "BlueprintEdgePk", "blueprint_edge_pk" },
            { "DeclaredBoundContentPk", "declared_bound_content_pk" },
            { "ReturnKind", "return_kind" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<BlueprintBoundedReturn> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<BlueprintBoundedReturn>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<BlueprintBoundedReturn>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY blueprint_edge_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [model].[blueprint_bounded_return]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToBlueprintBoundedReturnParameters(SqlCommand command, BlueprintBoundedReturn entity)
        {
            command.Parameters.AddWithValue("@CanonicalPointer", entity.CanonicalPointer);
            command.Parameters.AddWithValue("@CanonicalPointerKey", entity.CanonicalPointerKey ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@OwnerDefinitionPk", entity.OwnerDefinitionPk);
            command.Parameters.AddWithValue("@AuthorityDefinitionPk", entity.AuthorityDefinitionPk);
            command.Parameters.AddWithValue("@BlueprintEdgePk", entity.BlueprintEdgePk);
            command.Parameters.AddWithValue("@DeclaredBoundContentPk", entity.DeclaredBoundContentPk);
            command.Parameters.AddWithValue("@ReturnKind", entity.ReturnKind);
        }
        
    }
}

