//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EstateModel.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class EstateModelRepository : IEstateModelRepository
    {
        private readonly string _connectionString;

        public EstateModelRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(EstateModel entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [source].[estate_model] ([estate_snapshot_pk], [mapping_manifest_digest], [publication_state]) VALUES (@EstateSnapshotPk, @MappingManifestDigest, @PublicationState); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToEstateModelParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(EstateModel entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [source].[estate_model] SET
 [estate_snapshot_pk] = @EstateSnapshotPk, [mapping_manifest_digest] = @MappingManifestDigest, [publication_state] = @PublicationState WHERE [estate_model_pk] = @EstateModelPk", connection))
                {
                    connection.Open();

                    MapValuesToEstateModelParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(EstateModel entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [source].[estate_model] WHERE [estate_model_pk] = @EstateModelPk", connection))
                {
                    command.Parameters.AddWithValue("@EstateModelPk", entity.EstateModelPk);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<EstateModel?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]   WHERE [estate_model_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToEstateModelAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<EstateModel>> GetAllAsync()
        {
            var entities = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToEstateModelAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<EstateModel>> GetAnyAsync(QueryDetail<EstateModel> queryDetail)
        {
            var entities = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<EstateModel>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToEstateModelAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<EstateModel>> GetByEstateSnapshotPkAsync(long id)
        {
            List<EstateModel> results = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]   WHERE [estate_snapshot_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToEstateModelAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<EstateModel> MapReaderToEstateModelAsync(SqlDataReader reader)
        {
            return new EstateModel
            {
                EstateModelPk = reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                EstateSnapshotPk = reader.GetInt64(reader.GetOrdinal("estate_snapshot_pk")),
                MappingManifestDigest = (byte[])reader.GetValue(reader.GetOrdinal("mapping_manifest_digest")),
                PublicationState = reader.GetString(reader.GetOrdinal("publication_state"))
            };
        }
        
        public object Add(EstateModel entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [source].[estate_model] ([estate_snapshot_pk], [mapping_manifest_digest], [publication_state]) VALUES (@EstateSnapshotPk, @MappingManifestDigest, @PublicationState); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToEstateModelParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(EstateModel entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [source].[estate_model] SET
 [estate_snapshot_pk] = @EstateSnapshotPk, [mapping_manifest_digest] = @MappingManifestDigest, [publication_state] = @PublicationState WHERE [estate_model_pk] = @EstateModelPk", connection))
                {
                    connection.Open();

                    MapValuesToEstateModelParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(EstateModel entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [source].[estate_model] WHERE [estate_model_pk] = @EstateModelPk", connection))
                {
                    command.Parameters.AddWithValue("@EstateModelPk", entity.EstateModelPk);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public EstateModel? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]   WHERE [estate_model_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToEstateModel(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<EstateModel> GetAll()
        {
            var entities = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToEstateModel(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<EstateModel> GetAny(QueryDetail<EstateModel> queryDetail)
        {
            var entities = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<EstateModel>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToEstateModel(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<EstateModel> GetByEstateSnapshotPk(long id)
        {
            List<EstateModel> results = new List<EstateModel>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [source].[estate_model]   WHERE [estate_snapshot_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToEstateModel(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public EstateModel MapReaderToEstateModel(SqlDataReader reader)
        {
            return new EstateModel
            {
                EstateModelPk = reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                EstateSnapshotPk = reader.GetInt64(reader.GetOrdinal("estate_snapshot_pk")),
                MappingManifestDigest = (byte[])reader.GetValue(reader.GetOrdinal("mapping_manifest_digest")),
                PublicationState = reader.GetString(reader.GetOrdinal("publication_state"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "EstateModelPk", "estate_model_pk" },
            { "EstateSnapshotPk", "estate_snapshot_pk" },
            { "MappingManifestDigest", "mapping_manifest_digest" },
            { "PublicationState", "publication_state" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<EstateModel> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<EstateModel>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<EstateModel>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY estate_model_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [source].[estate_model]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToEstateModelParameters(SqlCommand command, EstateModel entity)
        {
            command.Parameters.AddWithValue("@EstateModelPk", entity.EstateModelPk);
            command.Parameters.AddWithValue("@EstateSnapshotPk", entity.EstateSnapshotPk);
            command.Parameters.AddWithValue("@MappingManifestDigest", entity.MappingManifestDigest);
            command.Parameters.AddWithValue("@PublicationState", entity.PublicationState);
        }
        
    }
}

