//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'MechanicVersion.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class MechanicVersionRepository : IMechanicVersionRepository
    {
        private readonly string _connectionString;

        public MechanicVersionRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(MechanicVersion entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[mechanic_version] ([_canonical_pointer], [_owner_definition_pk], [definition_digest], [definition_profile], [mechanic_kind], [mechanic_pk], [name], [object_kind], [semantic_object_definition_pk], [semantic_object_pk]) VALUES (@CanonicalPointer, @OwnerDefinitionPk, @DefinitionDigest, @DefinitionProfile, @MechanicKind, @MechanicPk, @Name, @ObjectKind, @SemanticObjectDefinitionPk, @SemanticObjectPk); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToMechanicVersionParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(MechanicVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[mechanic_version] SET
 [_canonical_pointer] = @CanonicalPointer, [_owner_definition_pk] = @OwnerDefinitionPk, [definition_digest] = @DefinitionDigest, [definition_profile] = @DefinitionProfile, [mechanic_kind] = @MechanicKind, [mechanic_pk] = @MechanicPk, [name] = @Name, [object_kind] = @ObjectKind, [semantic_object_definition_pk] = @SemanticObjectDefinitionPk, [semantic_object_pk] = @SemanticObjectPk WHERE [mechanic_version_pk] = @MechanicVersionPk", connection))
                {
                    connection.Open();

                    MapValuesToMechanicVersionParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(MechanicVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[mechanic_version] WHERE [mechanic_version_pk] = @MechanicVersionPk", connection))
                {
                    command.Parameters.AddWithValue("@MechanicVersionPk", entity.MechanicVersionPk);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<MechanicVersion?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [mechanic_version_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToMechanicVersionAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<MechanicVersion>> GetAllAsync()
        {
            var entities = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<MechanicVersion>> GetAnyAsync(QueryDetail<MechanicVersion> queryDetail)
        {
            var entities = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<MechanicVersion>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<MechanicVersion>> GetByOwnerDefinitionPkAsync(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [_owner_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<MechanicVersion>> GetByDefinitionDigestAsync(byte[] id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [definition_digest] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<MechanicVersion>> GetByMechanicPkAsync(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [mechanic_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<MechanicVersion>> GetByObjectKindAsync(string id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<MechanicVersion>> GetBySemanticObjectDefinitionPkAsync(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [semantic_object_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<MechanicVersion>> GetBySemanticObjectPkAsync(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToMechanicVersionAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<MechanicVersion> MapReaderToMechanicVersionAsync(SqlDataReader reader)
        {
            return new MechanicVersion
            {
                CanonicalPointer = reader.GetString(reader.GetOrdinal("_canonical_pointer")),
                CanonicalPointerKey = await reader.IsDBNullAsync(reader.GetOrdinal("_canonical_pointer_key")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("_canonical_pointer_key")),
                OwnerDefinitionPk = reader.GetInt64(reader.GetOrdinal("_owner_definition_pk")),
                DefinitionDigest = (byte[])reader.GetValue(reader.GetOrdinal("definition_digest")),
                DefinitionProfile = reader.GetString(reader.GetOrdinal("definition_profile")),
                MechanicKind = await reader.IsDBNullAsync(reader.GetOrdinal("mechanic_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("mechanic_kind")),
                MechanicPk = reader.GetInt64(reader.GetOrdinal("mechanic_pk")),
                MechanicVersionPk = reader.GetInt64(reader.GetOrdinal("mechanic_version_pk")),
                Name = await reader.IsDBNullAsync(reader.GetOrdinal("name")) ? (string?)null : reader.GetString(reader.GetOrdinal("name")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectDefinitionPk = reader.GetInt64(reader.GetOrdinal("semantic_object_definition_pk")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk"))
            };
        }
        
        public object Add(MechanicVersion entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[mechanic_version] ([_canonical_pointer], [_owner_definition_pk], [definition_digest], [definition_profile], [mechanic_kind], [mechanic_pk], [name], [object_kind], [semantic_object_definition_pk], [semantic_object_pk]) VALUES (@CanonicalPointer, @OwnerDefinitionPk, @DefinitionDigest, @DefinitionProfile, @MechanicKind, @MechanicPk, @Name, @ObjectKind, @SemanticObjectDefinitionPk, @SemanticObjectPk); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToMechanicVersionParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(MechanicVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[mechanic_version] SET
 [_canonical_pointer] = @CanonicalPointer, [_owner_definition_pk] = @OwnerDefinitionPk, [definition_digest] = @DefinitionDigest, [definition_profile] = @DefinitionProfile, [mechanic_kind] = @MechanicKind, [mechanic_pk] = @MechanicPk, [name] = @Name, [object_kind] = @ObjectKind, [semantic_object_definition_pk] = @SemanticObjectDefinitionPk, [semantic_object_pk] = @SemanticObjectPk WHERE [mechanic_version_pk] = @MechanicVersionPk", connection))
                {
                    connection.Open();

                    MapValuesToMechanicVersionParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(MechanicVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[mechanic_version] WHERE [mechanic_version_pk] = @MechanicVersionPk", connection))
                {
                    command.Parameters.AddWithValue("@MechanicVersionPk", entity.MechanicVersionPk);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public MechanicVersion? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [mechanic_version_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToMechanicVersion(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<MechanicVersion> GetAll()
        {
            var entities = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<MechanicVersion> GetAny(QueryDetail<MechanicVersion> queryDetail)
        {
            var entities = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<MechanicVersion>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<MechanicVersion> GetByOwnerDefinitionPk(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [_owner_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<MechanicVersion> GetByDefinitionDigest(byte[] id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [definition_digest] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<MechanicVersion> GetByMechanicPk(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [mechanic_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<MechanicVersion> GetByObjectKind(string id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<MechanicVersion> GetBySemanticObjectDefinitionPk(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [semantic_object_definition_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<MechanicVersion> GetBySemanticObjectPk(long id)
        {
            List<MechanicVersion> results = new List<MechanicVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[mechanic_version]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToMechanicVersion(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public MechanicVersion MapReaderToMechanicVersion(SqlDataReader reader)
        {
            return new MechanicVersion
            {
                CanonicalPointer = reader.GetString(reader.GetOrdinal("_canonical_pointer")),
                CanonicalPointerKey = reader.IsDBNull(reader.GetOrdinal("_canonical_pointer_key")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("_canonical_pointer_key")),
                OwnerDefinitionPk = reader.GetInt64(reader.GetOrdinal("_owner_definition_pk")),
                DefinitionDigest = (byte[])reader.GetValue(reader.GetOrdinal("definition_digest")),
                DefinitionProfile = reader.GetString(reader.GetOrdinal("definition_profile")),
                MechanicKind = reader.IsDBNull(reader.GetOrdinal("mechanic_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("mechanic_kind")),
                MechanicPk = reader.GetInt64(reader.GetOrdinal("mechanic_pk")),
                MechanicVersionPk = reader.GetInt64(reader.GetOrdinal("mechanic_version_pk")),
                Name = reader.IsDBNull(reader.GetOrdinal("name")) ? (string?)null : reader.GetString(reader.GetOrdinal("name")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectDefinitionPk = reader.GetInt64(reader.GetOrdinal("semantic_object_definition_pk")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CanonicalPointer", "_canonical_pointer" },
            { "CanonicalPointerKey", "_canonical_pointer_key" },
            { "OwnerDefinitionPk", "_owner_definition_pk" },
            { "DefinitionDigest", "definition_digest" },
            { "DefinitionProfile", "definition_profile" },
            { "MechanicKind", "mechanic_kind" },
            { "MechanicPk", "mechanic_pk" },
            { "MechanicVersionPk", "mechanic_version_pk" },
            { "Name", "name" },
            { "ObjectKind", "object_kind" },
            { "SemanticObjectDefinitionPk", "semantic_object_definition_pk" },
            { "SemanticObjectPk", "semantic_object_pk" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<MechanicVersion> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<MechanicVersion>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<MechanicVersion>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY mechanic_version_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [model].[mechanic_version]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToMechanicVersionParameters(SqlCommand command, MechanicVersion entity)
        {
            command.Parameters.AddWithValue("@CanonicalPointer", entity.CanonicalPointer);
            command.Parameters.AddWithValue("@CanonicalPointerKey", entity.CanonicalPointerKey ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@OwnerDefinitionPk", entity.OwnerDefinitionPk);
            command.Parameters.AddWithValue("@DefinitionDigest", entity.DefinitionDigest);
            command.Parameters.AddWithValue("@DefinitionProfile", entity.DefinitionProfile);
            command.Parameters.AddWithValue("@MechanicKind", entity.MechanicKind ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@MechanicPk", entity.MechanicPk);
            command.Parameters.AddWithValue("@MechanicVersionPk", entity.MechanicVersionPk);
            command.Parameters.AddWithValue("@Name", entity.Name ?? (object)DBNull.Value);
            command.Parameters.AddWithValue("@ObjectKind", entity.ObjectKind);
            command.Parameters.AddWithValue("@SemanticObjectDefinitionPk", entity.SemanticObjectDefinitionPk);
            command.Parameters.AddWithValue("@SemanticObjectPk", entity.SemanticObjectPk);
        }
        
    }
}

