//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'SchemaVersion.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class SchemaVersionRepository : ISchemaVersionRepository
    {
        private readonly string _connectionString;

        public SchemaVersionRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(SchemaVersion entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [media].[schema_version] ([digest], [installed_at], [version]) VALUES (@Digest, @InstalledAt, @Version); SELECT @Version;", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToSchemaVersionParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(SchemaVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [media].[schema_version] SET
 [digest] = @Digest, [installed_at] = @InstalledAt WHERE [version] = @Version", connection))
                {
                    connection.Open();

                    MapValuesToSchemaVersionParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(SchemaVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [media].[schema_version] WHERE [version] = @Version", connection))
                {
                    command.Parameters.AddWithValue("@Version", entity.Version);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<SchemaVersion?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[schema_version]   WHERE [version] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToSchemaVersionAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<SchemaVersion>> GetAllAsync()
        {
            var entities = new List<SchemaVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[schema_version]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToSchemaVersionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<SchemaVersion>> GetAnyAsync(QueryDetail<SchemaVersion> queryDetail)
        {
            var entities = new List<SchemaVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<SchemaVersion>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToSchemaVersionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        
        public async Task<SchemaVersion> MapReaderToSchemaVersionAsync(SqlDataReader reader)
        {
            return new SchemaVersion
            {
                Digest = (byte[])reader.GetValue(reader.GetOrdinal("digest")),
                InstalledAt = reader.GetDateTime(reader.GetOrdinal("installed_at")),
                Version = reader.GetString(reader.GetOrdinal("version"))
            };
        }
        
        public object Add(SchemaVersion entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [media].[schema_version] ([digest], [installed_at], [version]) VALUES (@Digest, @InstalledAt, @Version); SELECT @Version;", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToSchemaVersionParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(SchemaVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [media].[schema_version] SET
 [digest] = @Digest, [installed_at] = @InstalledAt WHERE [version] = @Version", connection))
                {
                    connection.Open();

                    MapValuesToSchemaVersionParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(SchemaVersion entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [media].[schema_version] WHERE [version] = @Version", connection))
                {
                    command.Parameters.AddWithValue("@Version", entity.Version);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public SchemaVersion? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[schema_version]   WHERE [version] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToSchemaVersion(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<SchemaVersion> GetAll()
        {
            var entities = new List<SchemaVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[schema_version]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToSchemaVersion(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<SchemaVersion> GetAny(QueryDetail<SchemaVersion> queryDetail)
        {
            var entities = new List<SchemaVersion>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<SchemaVersion>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToSchemaVersion(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        
        public SchemaVersion MapReaderToSchemaVersion(SqlDataReader reader)
        {
            return new SchemaVersion
            {
                Digest = (byte[])reader.GetValue(reader.GetOrdinal("digest")),
                InstalledAt = reader.GetDateTime(reader.GetOrdinal("installed_at")),
                Version = reader.GetString(reader.GetOrdinal("version"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Digest", "digest" },
            { "InstalledAt", "installed_at" },
            { "Version", "version" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<SchemaVersion> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<SchemaVersion>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<SchemaVersion>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY version";

            return $@"SELECT e.* FROM (SELECT * FROM [media].[schema_version]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToSchemaVersionParameters(SqlCommand command, SchemaVersion entity)
        {
            command.Parameters.AddWithValue("@Digest", entity.Digest);
            command.Parameters.AddWithValue("@InstalledAt", entity.InstalledAt);
            command.Parameters.AddWithValue("@Version", entity.Version);
        }
        
    }
}

