//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'SelectionHistory.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class SelectionHistoryRepository : ISelectionHistoryRepository
    {
        private readonly string _connectionString;

        public SelectionHistoryRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(SelectionHistory entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [media].[selection_history] ([binding_id], [requirement_id], [review_id], [selected_at]) VALUES (@BindingId, @RequirementId, @ReviewId, @SelectedAt); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToSelectionHistoryParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(SelectionHistory entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [media].[selection_history] SET
 [binding_id] = @BindingId, [requirement_id] = @RequirementId, [review_id] = @ReviewId, [selected_at] = @SelectedAt WHERE [selection_id] = @SelectionId", connection))
                {
                    connection.Open();

                    MapValuesToSelectionHistoryParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(SelectionHistory entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [media].[selection_history] WHERE [selection_id] = @SelectionId", connection))
                {
                    command.Parameters.AddWithValue("@SelectionId", entity.SelectionId);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<SelectionHistory?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [selection_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToSelectionHistoryAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<SelectionHistory>> GetAllAsync()
        {
            var entities = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToSelectionHistoryAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<SelectionHistory>> GetAnyAsync(QueryDetail<SelectionHistory> queryDetail)
        {
            var entities = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<SelectionHistory>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToSelectionHistoryAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<SelectionHistory>> GetByBindingIdAsync(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [binding_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToSelectionHistoryAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<SelectionHistory>> GetByRequirementIdAsync(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [requirement_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToSelectionHistoryAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<SelectionHistory>> GetByReviewIdAsync(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [review_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToSelectionHistoryAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<SelectionHistory> MapReaderToSelectionHistoryAsync(SqlDataReader reader)
        {
            return new SelectionHistory
            {
                BindingId = reader.GetInt64(reader.GetOrdinal("binding_id")),
                RequirementId = reader.GetInt64(reader.GetOrdinal("requirement_id")),
                ReviewId = reader.GetInt64(reader.GetOrdinal("review_id")),
                SelectedAt = reader.GetDateTime(reader.GetOrdinal("selected_at")),
                SelectionId = reader.GetInt64(reader.GetOrdinal("selection_id"))
            };
        }
        
        public object Add(SelectionHistory entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [media].[selection_history] ([binding_id], [requirement_id], [review_id], [selected_at]) VALUES (@BindingId, @RequirementId, @ReviewId, @SelectedAt); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToSelectionHistoryParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(SelectionHistory entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [media].[selection_history] SET
 [binding_id] = @BindingId, [requirement_id] = @RequirementId, [review_id] = @ReviewId, [selected_at] = @SelectedAt WHERE [selection_id] = @SelectionId", connection))
                {
                    connection.Open();

                    MapValuesToSelectionHistoryParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(SelectionHistory entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [media].[selection_history] WHERE [selection_id] = @SelectionId", connection))
                {
                    command.Parameters.AddWithValue("@SelectionId", entity.SelectionId);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public SelectionHistory? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [selection_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToSelectionHistory(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<SelectionHistory> GetAll()
        {
            var entities = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToSelectionHistory(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<SelectionHistory> GetAny(QueryDetail<SelectionHistory> queryDetail)
        {
            var entities = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<SelectionHistory>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToSelectionHistory(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<SelectionHistory> GetByBindingId(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [binding_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToSelectionHistory(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<SelectionHistory> GetByRequirementId(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [requirement_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToSelectionHistory(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<SelectionHistory> GetByReviewId(long id)
        {
            List<SelectionHistory> results = new List<SelectionHistory>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [media].[selection_history]   WHERE [review_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToSelectionHistory(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public SelectionHistory MapReaderToSelectionHistory(SqlDataReader reader)
        {
            return new SelectionHistory
            {
                BindingId = reader.GetInt64(reader.GetOrdinal("binding_id")),
                RequirementId = reader.GetInt64(reader.GetOrdinal("requirement_id")),
                ReviewId = reader.GetInt64(reader.GetOrdinal("review_id")),
                SelectedAt = reader.GetDateTime(reader.GetOrdinal("selected_at")),
                SelectionId = reader.GetInt64(reader.GetOrdinal("selection_id"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "BindingId", "binding_id" },
            { "RequirementId", "requirement_id" },
            { "ReviewId", "review_id" },
            { "SelectedAt", "selected_at" },
            { "SelectionId", "selection_id" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<SelectionHistory> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<SelectionHistory>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<SelectionHistory>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY selection_id";

            return $@"SELECT e.* FROM (SELECT * FROM [media].[selection_history]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToSelectionHistoryParameters(SqlCommand command, SelectionHistory entity)
        {
            command.Parameters.AddWithValue("@BindingId", entity.BindingId);
            command.Parameters.AddWithValue("@RequirementId", entity.RequirementId);
            command.Parameters.AddWithValue("@ReviewId", entity.ReviewId);
            command.Parameters.AddWithValue("@SelectedAt", entity.SelectedAt);
            command.Parameters.AddWithValue("@SelectionId", entity.SelectionId);
        }
        
    }
}

