//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Transformation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class TransformationRepository : ITransformationRepository
    {
        private readonly string _connectionString;

        public TransformationRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<object> AddAsync(Transformation entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[transformation] ([namespace_pk], [object_kind], [semantic_object_pk], [transformation_id]) VALUES (@NamespacePk, @ObjectKind, @SemanticObjectPk, @TransformationId); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToTransformationParameters(command, entity);

                    object? result = await command.ExecuteScalarAsync();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public async Task UpdateAsync(Transformation entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[transformation] SET
 [namespace_pk] = @NamespacePk, [object_kind] = @ObjectKind, [semantic_object_pk] = @SemanticObjectPk, [transformation_id] = @TransformationId WHERE [transformation_pk] = @TransformationPk", connection))
                {
                    connection.Open();

                    MapValuesToTransformationParameters(command, entity);

                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public async Task DeleteAsync(Transformation entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[transformation] WHERE [transformation_pk] = @TransformationPk", connection))
                {
                    command.Parameters.AddWithValue("@TransformationPk", entity.TransformationPk);
                    connection.Open();
                    await command.ExecuteNonQueryAsync();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public async Task<Transformation?> GetByIdAsync(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [transformation_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToTransformationAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<Transformation>> GetAllAsync()
        {
            var entities = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<Transformation>> GetAnyAsync(QueryDetail<Transformation> queryDetail)
        {
            var entities = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<Transformation>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<List<Transformation>> GetByNamespacePkAsync(long id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [namespace_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Transformation>> GetByObjectKindAsync(string id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Transformation>> GetBySemanticObjectPkAsync(long id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public async Task<List<Transformation>> GetByTransformationIdAsync(string id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [transformation_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(await MapReaderToTransformationAsync(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<Transformation> MapReaderToTransformationAsync(SqlDataReader reader)
        {
            return new Transformation
            {
                NamespacePk = reader.GetInt64(reader.GetOrdinal("namespace_pk")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk")),
                TransformationId = reader.GetString(reader.GetOrdinal("transformation_id")),
                TransformationPk = reader.GetInt64(reader.GetOrdinal("transformation_pk"))
            };
        }
        
        public object Add(Transformation entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "The provided entity cannot be null.");
            }

            try {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("INSERT INTO [model].[transformation] ([namespace_pk], [object_kind], [semantic_object_pk], [transformation_id]) VALUES (@NamespacePk, @ObjectKind, @SemanticObjectPk, @TransformationId); SELECT SCOPE_IDENTITY();", connection))
                {
                    command.CommandTimeout = 30; // Setting command timeout
                    connection.Open();

                    MapValuesToTransformationParameters(command, entity);

                    object? result = command.ExecuteScalar();
                    return result!;
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error adding entity to the database: " + ex.Message, ex);
            }
        }
        
        public void Update(Transformation entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"UPDATE [model].[transformation] SET
 [namespace_pk] = @NamespacePk, [object_kind] = @ObjectKind, [semantic_object_pk] = @SemanticObjectPk, [transformation_id] = @TransformationId WHERE [transformation_pk] = @TransformationPk", connection))
                {
                    connection.Open();

                    MapValuesToTransformationParameters(command, entity);

                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error updating entity in the database: " + ex.Message, ex);
            }
        }
        
        public void Delete(Transformation entity)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("DELETE FROM [model].[transformation] WHERE [transformation_pk] = @TransformationPk", connection))
                {
                    command.Parameters.AddWithValue("@TransformationPk", entity.TransformationPk);
                    connection.Open();
                    command.ExecuteNonQuery();
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error deleting entity from the table: " + ex.Message, ex);
            }
        }
        
        public Transformation? GetById(object id)  // Consider changing 'int id' to a more generic type
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [transformation_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToTransformation(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<Transformation> GetAll()
        {
            var entities = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<Transformation> GetAny(QueryDetail<Transformation> queryDetail)
        {
            var entities = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<Transformation>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public List<Transformation> GetByNamespacePk(long id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [namespace_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Transformation> GetByObjectKind(string id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [object_kind] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Transformation> GetBySemanticObjectPk(long id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [semantic_object_pk] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        public List<Transformation> GetByTransformationId(string id)
        {
            List<Transformation> results = new List<Transformation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [model].[transformation]   WHERE [transformation_id] = @Id", connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            results.Add(MapReaderToTransformation(reader));
                        }
                    }
                }
                return results;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public Transformation MapReaderToTransformation(SqlDataReader reader)
        {
            return new Transformation
            {
                NamespacePk = reader.GetInt64(reader.GetOrdinal("namespace_pk")),
                ObjectKind = reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectPk = reader.GetInt64(reader.GetOrdinal("semantic_object_pk")),
                TransformationId = reader.GetString(reader.GetOrdinal("transformation_id")),
                TransformationPk = reader.GetInt64(reader.GetOrdinal("transformation_pk"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "NamespacePk", "namespace_pk" },
            { "ObjectKind", "object_kind" },
            { "SemanticObjectPk", "semantic_object_pk" },
            { "TransformationId", "transformation_id" },
            { "TransformationPk", "transformation_pk" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<Transformation> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<Transformation>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<Transformation>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY transformation_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [model].[transformation]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public void MapValuesToTransformationParameters(SqlCommand command, Transformation entity)
        {
            command.Parameters.AddWithValue("@NamespacePk", entity.NamespacePk);
            command.Parameters.AddWithValue("@ObjectKind", entity.ObjectKind);
            command.Parameters.AddWithValue("@SemanticObjectPk", entity.SemanticObjectPk);
            command.Parameters.AddWithValue("@TransformationId", entity.TransformationId);
            command.Parameters.AddWithValue("@TransformationPk", entity.TransformationPk);
        }
        
    }
}

