//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadProviderConformanceSignal.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class AnalysisReadProviderConformanceSignal
    {
        public string ResultSet { get; set; } = default!;
        public long? EstateModelPk { get; set; }
        public long? ReferencedPairs { get; set; }
        public long? ReferencedProviders { get; set; }
        public long? AuthorityOnlyPairs { get; set; }
        public long? UndeclaredPairs { get; set; }
        public long? AuthorityEntries { get; set; }
        public long? RelationBindingResolved { get; set; }
        public long? EvidenceBindingNamedByTransformation { get; set; }
        public long? RelationEndpointResolved { get; set; }
        public long? EvidenceEndpointInPort { get; set; }
        public long? ApplicationRefEntries { get; set; }
        public long? RelationApplicationResolved { get; set; }
        public long? EvidenceApplicationSelected { get; set; }
        public long? BindingCheckPortSelfSatisfied { get; set; }
        public long? RelationEvidenceDisagreements { get; set; }
        public long? ProvidersNoPciNoRole { get; set; }
        public long? OverlayPresenceWithoutContent { get; set; }
        public long? ConfigRefsWithoutParticipation { get; set; }
        public long? GateProviderRoleViolations { get; set; }
        public long? GateProviderViolations { get; set; }
        public long? CatalogEntries { get; set; }
        public long? CatalogBodyDrift { get; set; }
        public string? RelationBodySha256 { get; set; }
        public string? GateBodySha256 { get; set; }
        public string? ProfileDefinitionDigest { get; set; }
        public string? SignalDigest { get; set; }
        public string? ExpectedSignalDigest { get; set; }
        public string? Disposition { get; set; }
    }
}