//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareProviderPort.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ModelDeclareProviderPort
    {
        public string ResultSet { get; set; } = default!;
        public string? NamespaceId { get; set; }
        public string? PortId { get; set; }
        public string? PlatformCapabilityId { get; set; }
        public long? ObjectPk { get; set; }
        public long? DefinitionPk { get; set; }
    }
}