//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelBindPortFromContract.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ModelBindPortFromContract
    {
        public string Action { get; set; } = default!;
        public string? CapabilityId { get; set; }
        public string? MechanicId { get; set; }
        public string? ProviderId { get; set; }
        public string? PlatformCapabilityId { get; set; }
        public long? DefinitionAfter { get; set; }
        public long? PortVersionPk { get; set; }
    }
}