//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelConfigureContract.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ModelConfigureContract
    {
        public string Action { get; set; } = default!;
        public string? CapabilityId { get; set; }
        public string? Face { get; set; }
        public long? ContractVersionBefore { get; set; }
        public long? ContractVersionAfter { get; set; }
        public string? PayloadPropertiesBefore { get; set; }
        public string? PayloadPropertiesAfter { get; set; }
    }
}