//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareCapabilityInterface.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ModelDeclareCapabilityInterface
    {
        public string Action { get; set; } = default!;
        public long? CapabilityPk { get; set; }
        public long? VersionPk { get; set; }
        public long? DefinitionPk { get; set; }
        public string? Digest { get; set; }
    }
}