//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelInspectCapability.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ModelInspectCapability
    {
        public string ResultSet { get; set; } = default!;
        public string CapabilityId { get; set; } = default!;
        public long? CapabilityVersionPk { get; set; }
        public long? CapabilityDefinitionPk { get; set; }
        public string? CapabilityDefinitionDigest { get; set; }
        public string? Intent { get; set; }
    }
}