//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EvidenceCompleteRun.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.Identity.DAL.Interfaces;
using SFX.Identity.DAL.Helpers;
using SFX.Identity.DAL.Models;

namespace SFX.Identity.DAL.Repositories
{
    public partial class EvidenceCompleteRunRepository : IEvidenceCompleteRunRepository
    {
        private readonly string _connectionString;

        public EvidenceCompleteRunRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<EvidenceCompleteRun>> ExecuteAsync(string runId, string writerId, string runJson, string graphJson, string outputJson, long latestCursor)
        {
            var entities = new List<EvidenceCompleteRun>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[evidence].[complete_run]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@run_id", runId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@writer_id", writerId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@run_json", runJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@graph_json", graphJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@output_json", outputJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@latest_cursor", latestCursor);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (await reader.NextResultAsync() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToEvidenceCompleteRun(row));
                        }
                    }
                    return new ProcedureCallResult<EvidenceCompleteRun>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure evidence.complete_run: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<EvidenceCompleteRun> Execute(string runId, string writerId, string runJson, string graphJson, string outputJson, long latestCursor)
        {
            var entities = new List<EvidenceCompleteRun>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[evidence].[complete_run]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@run_id", runId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@writer_id", writerId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@run_json", runJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@graph_json", graphJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@output_json", outputJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@latest_cursor", latestCursor);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (reader.NextResult() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToEvidenceCompleteRun(row));
                        }
                    }
                    return new ProcedureCallResult<EvidenceCompleteRun>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure evidence.complete_run: " + ex.Message, ex);
            }
        }
        
        public EvidenceCompleteRun MapRowToEvidenceCompleteRun(DataRow row)
        {
            return new EvidenceCompleteRun
            {
                TraceComplete = (bool)row["trace_complete"],
                MaterialDigest = (byte[])row["material_digest"]
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

