//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EvidenceRegisterRun.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.Identity.DAL.Interfaces;
using SFX.Identity.DAL.Helpers;
using SFX.Identity.DAL.Models;

namespace SFX.Identity.DAL.Repositories
{
    public partial class EvidenceRegisterRunRepository : IEvidenceRegisterRunRepository
    {
        private readonly string _connectionString;

        public EvidenceRegisterRunRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<EvidenceRegisterRun>> ExecuteAsync(string runId, Guid principalId, Guid sessionId, string capabilityId, string namespaceId, string writerId)
        {
            var entities = new List<EvidenceRegisterRun>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[evidence].[register_run]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@run_id", runId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@principal_id", principalId);
                    command.Parameters.AddWithValue("@session_id", sessionId);
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@namespace_id", namespaceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@writer_id", writerId ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (await reader.NextResultAsync() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToEvidenceRegisterRun(row));
                        }
                    }
                    return new ProcedureCallResult<EvidenceRegisterRun>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure evidence.register_run: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<EvidenceRegisterRun> Execute(string runId, Guid principalId, Guid sessionId, string capabilityId, string namespaceId, string writerId)
        {
            var entities = new List<EvidenceRegisterRun>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[evidence].[register_run]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@run_id", runId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@principal_id", principalId);
                    command.Parameters.AddWithValue("@session_id", sessionId);
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@namespace_id", namespaceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@writer_id", writerId ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (reader.NextResult() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToEvidenceRegisterRun(row));
                        }
                    }
                    return new ProcedureCallResult<EvidenceRegisterRun>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure evidence.register_run: " + ex.Message, ex);
            }
        }
        
        public EvidenceRegisterRun MapRowToEvidenceRegisterRun(DataRow row)
        {
            return new EvidenceRegisterRun
            {
                RunId = (string)row["run_id"],
                AdmittedAt = (DateTimeOffset)row["admitted_at"]
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

