//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvReferences.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class AnalysisFvReferences
    {
        public string? ReferencingObjectKind { get; set; }
        public string? ReferencingNamespaceId { get; set; }
        public string? ReferencingDeclaredId { get; set; }
        public long? ReferencingDefinitionPk { get; set; }
        public byte[]? ReferencingDigest { get; set; }
        public string? SiteClass { get; set; }
        public string? SiteTable { get; set; }
        public string? SiteColumn { get; set; }
        public string? SiteJsonPath { get; set; }
        public string? MatchedValue { get; set; }
        public string? MatchQuality { get; set; }
        public string? Scope { get; set; }
        public string? ScanState { get; set; }
    }
}