//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeInstallAdmission.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ProbeInstallAdmission
    {
        public long PortVersionPk { get; set; }
        public byte[] PortDefinitionDigest { get; set; } = default!;
        public long PortPk { get; set; }
        public string PortId { get; set; } = default!;
        public string? PlatformCapabilityId { get; set; }
        public long SemanticObjectDefinitionPk { get; set; }
        public long CanonicalContentPk { get; set; }
        public byte[] ContentDigest { get; set; } = default!;
        public long ByteLength { get; set; }
    }
}