//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeCurrentModelPin.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ProbeCurrentModelPin
    {
        public long EstateModelPk { get; set; }
        public byte SingletonId { get; set; }
    }
}