//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeReachTransformations.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ProbeReachTransformations
    {
        public long TransformationPk { get; set; }
        public string TransformationId { get; set; } = default!;
        public long SemanticObjectDefinitionPk { get; set; }
        public byte[] DefinitionDigest { get; set; } = default!;
        public long ContentObjectPk { get; set; }
        public long ByteLength { get; set; }
    }
}