//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeProviderAuthor.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ProbeProviderAuthor
    {
        public long ProviderPk { get; set; }
        public string ProviderId { get; set; } = default!;
        public long ProviderDefinitionPk { get; set; }
        public byte[] DefinitionDigest { get; set; } = default!;
        public string? ProviderDefinitionName { get; set; }
        public long ContentObjectPk { get; set; }
        public long ByteLength { get; set; }
    }
}