//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadCapabilityOperations.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisReadCapabilityOperationsRepository : IAnalysisReadCapabilityOperationsRepository
    {
        private readonly string _connectionString;

        public AnalysisReadCapabilityOperationsRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<AnalysisReadCapabilityOperations>> ExecuteAsync(string capabilityId, long estateModelPk)
        {
            var entities = new List<AnalysisReadCapabilityOperations>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[analysis].[read_capability_operations]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_model_pk", estateModelPk);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisReadCapabilityOperations(reader));
                        }
                        while (await reader.NextResultAsync())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<AnalysisReadCapabilityOperations>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure analysis.read_capability_operations: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<AnalysisReadCapabilityOperations> Execute(string capabilityId, long estateModelPk)
        {
            var entities = new List<AnalysisReadCapabilityOperations>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[analysis].[read_capability_operations]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_model_pk", estateModelPk);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisReadCapabilityOperations(reader));
                        }
                        while (reader.NextResult())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<AnalysisReadCapabilityOperations>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure analysis.read_capability_operations: " + ex.Message, ex);
            }
        }
        
        public AnalysisReadCapabilityOperations MapReaderToAnalysisReadCapabilityOperations(SqlDataReader reader)
        {
            return new AnalysisReadCapabilityOperations
            {
                ResultSet = reader.GetString(reader.GetOrdinal("result_set")),
                CapabilityId = reader.IsDBNull(reader.GetOrdinal("capability_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("capability_id")),
                Operations = reader.IsDBNull(reader.GetOrdinal("operations")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("operations")),
                InvokePort = reader.IsDBNull(reader.GetOrdinal("invoke_port")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("invoke_port")),
                InvokeScenario = reader.IsDBNull(reader.GetOrdinal("invoke_scenario")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("invoke_scenario")),
                OtherKinds = reader.IsDBNull(reader.GetOrdinal("other_kinds")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("other_kinds")),
                UnboundInvokePort = reader.IsDBNull(reader.GetOrdinal("unbound_invoke_port")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("unbound_invoke_port")),
                ScenarioVersions = reader.IsDBNull(reader.GetOrdinal("scenario_versions")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("scenario_versions")),
                AuthorityVersions = reader.IsDBNull(reader.GetOrdinal("authority_versions")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("authority_versions"))
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

