//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisReadProviderDetails.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisReadProviderDetailsRepository : IAnalysisReadProviderDetailsRepository
    {
        private readonly string _connectionString;

        public AnalysisReadProviderDetailsRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<AnalysisReadProviderDetails>> ExecuteAsync(string providerId, long? estateModelPk = null)
        {
            var entities = new List<AnalysisReadProviderDetails>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[analysis].[read_provider_details]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@provider_id", providerId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_model_pk", estateModelPk ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (await reader.NextResultAsync() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToAnalysisReadProviderDetails(row));
                        }
                    }
                    return new ProcedureCallResult<AnalysisReadProviderDetails>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure analysis.read_provider_details: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<AnalysisReadProviderDetails> Execute(string providerId, long? estateModelPk = null)
        {
            var entities = new List<AnalysisReadProviderDetails>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[analysis].[read_provider_details]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@provider_id", providerId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_model_pk", estateModelPk ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (reader.NextResult() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToAnalysisReadProviderDetails(row));
                        }
                    }
                    return new ProcedureCallResult<AnalysisReadProviderDetails>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure analysis.read_provider_details: " + ex.Message, ex);
            }
        }
        
        public AnalysisReadProviderDetails MapRowToAnalysisReadProviderDetails(DataRow row)
        {
            return new AnalysisReadProviderDetails
            {
                ResultSet = (string)row["result_set"],
                ProviderId = (string)row["provider_id"],
                NamespaceId = (string)row["namespace_id"],
                ProviderPk = (long)row["provider_pk"],
                SemanticObjectPk = (long)row["semantic_object_pk"],
                ProviderDefinitionPk = (long)row["provider_definition_pk"],
                DeclaredName = row.IsNull("declared_name") ? (string?)null : (string)row["declared_name"],
                DeclarationProfile = (string)row["declaration_profile"],
                DefinitionDigest = row.IsNull("definition_digest") ? (string?)null : (string)row["definition_digest"],
                Label = row.IsNull("label") ? (string?)null : (string)row["label"],
                DeclaredId = (string)row["declared_id"],
                ByteLength = row.IsNull("byte_length") ? (long?)null : (long)row["byte_length"],
                ProviderRole = row.IsNull("provider_role") ? (string?)null : (string)row["provider_role"],
                ProviderClass = (string)row["provider_class"],
                HasModuleOrExport = row.IsNull("has_module_or_export") ? (bool?)null : (bool)row["has_module_or_export"],
                PciCount = row.IsNull("pci_count") ? (int?)null : (int)row["pci_count"],
                OperationsCount = row.IsNull("operations_count") ? (int?)null : (int)row["operations_count"],
                SourcePropertyCount = row.IsNull("source_property_count") ? (int?)null : (int)row["source_property_count"],
                CandidateCapabilitiesCount = row.IsNull("candidate_capabilities_count") ? (int?)null : (int)row["candidate_capabilities_count"],
                CapabilitiesCount = row.IsNull("capabilities_count") ? (int?)null : (int)row["capabilities_count"],
                OverlayReferenceCount = row.IsNull("overlay_reference_count") ? (int?)null : (int)row["overlay_reference_count"],
                OverlayTopLevelReferenceCount = row.IsNull("overlay_top_level_reference_count") ? (int?)null : (int)row["overlay_top_level_reference_count"],
                OverlayAuthorityReferenceCount = row.IsNull("overlay_authority_reference_count") ? (int?)null : (int)row["overlay_authority_reference_count"],
                ResolvedProviderAuthorityCount = row.IsNull("resolved_provider_authority_count") ? (int?)null : (int)row["resolved_provider_authority_count"],
                ResolvedBindingReferenceCount = row.IsNull("resolved_binding_reference_count") ? (int?)null : (int)row["resolved_binding_reference_count"],
                ResolvedEndpointAuthorityCount = row.IsNull("resolved_endpoint_authority_count") ? (int?)null : (int)row["resolved_endpoint_authority_count"],
                ResolvedApplicationRefCount = row.IsNull("resolved_application_ref_count") ? (int?)null : (int)row["resolved_application_ref_count"],
                RoleEvidenceStatus = row.IsNull("role_evidence_status") ? (string?)null : (string)row["role_evidence_status"],
                DefinitionGenerations = row.IsNull("definition_generations") ? (int?)null : (int)row["definition_generations"],
                SelectedGenerations = row.IsNull("selected_generations") ? (int?)null : (int)row["selected_generations"]
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

