//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelConfigureContract.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class ModelConfigureContractRepository : IModelConfigureContractRepository
    {
        private readonly string _connectionString;

        public ModelConfigureContractRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<ModelConfigureContract>> ExecuteAsync(string capabilityId, string? face = null, string? addPropertiesJson = null, string? removePropertiesJson = null, bool? required = null)
        {
            var entities = new List<ModelConfigureContract>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_contract]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@face", face ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@add_properties_json", addPropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@remove_properties_json", removePropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@required", required ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (await reader.NextResultAsync() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToModelConfigureContract(row));
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureContract>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_contract: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<ModelConfigureContract> Execute(string capabilityId, string? face = null, string? addPropertiesJson = null, string? removePropertiesJson = null, bool? required = null)
        {
            var entities = new List<ModelConfigureContract>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_contract]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@face", face ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@add_properties_json", addPropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@remove_properties_json", removePropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@required", required ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (reader.NextResult() == false)
                            {
                                break;
                            }
                        }
                    }
                    if (resultSets.Count > 0)
                    {
                        foreach (DataRow row in resultSets[0].Rows)
                        {
                            entities.Add(MapRowToModelConfigureContract(row));
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureContract>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_contract: " + ex.Message, ex);
            }
        }
        
        public ModelConfigureContract MapRowToModelConfigureContract(DataRow row)
        {
            return new ModelConfigureContract
            {
                Action = (string)row["action"],
                CapabilityId = row.IsNull("capability_id") ? (string?)null : (string)row["capability_id"],
                Face = row.IsNull("face") ? (string?)null : (string)row["face"],
                ContractVersionBefore = row.IsNull("contract_version_before") ? (long?)null : (long)row["contract_version_before"],
                ContractVersionAfter = row.IsNull("contract_version_after") ? (long?)null : (long)row["contract_version_after"],
                PayloadPropertiesBefore = row.IsNull("payload_properties_before") ? (string?)null : (string)row["payload_properties_before"],
                PayloadPropertiesAfter = row.IsNull("payload_properties_after") ? (string?)null : (string)row["payload_properties_after"]
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

