//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelConfigureInterface.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class ModelConfigureInterfaceRepository : IModelConfigureInterfaceRepository
    {
        private readonly string _connectionString;

        public ModelConfigureInterfaceRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<ModelConfigureInterface>> ExecuteAsync(string capabilityId, string inputType, string inputContract, string inputPath, string displaySelect, string displayAs, string defaultsJson, string cliJson)
        {
            var entities = new List<ModelConfigureInterface>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_interface]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_type", inputType ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_contract", inputContract ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_path", inputPath ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@display_select", displaySelect ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@display_as", displayAs ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@defaults_json", defaultsJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@cli_json", cliJson ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToModelConfigureInterface(reader));
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureInterface>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_interface: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<ModelConfigureInterface> Execute(string capabilityId, string inputType, string inputContract, string inputPath, string displaySelect, string displayAs, string defaultsJson, string cliJson)
        {
            var entities = new List<ModelConfigureInterface>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_interface]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_type", inputType ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_contract", inputContract ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@input_path", inputPath ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@display_select", displaySelect ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@display_as", displayAs ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@defaults_json", defaultsJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@cli_json", cliJson ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToModelConfigureInterface(reader));
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureInterface>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_interface: " + ex.Message, ex);
            }
        }
        
        public ModelConfigureInterface MapReaderToModelConfigureInterface(SqlDataReader reader)
        {
            return new ModelConfigureInterface
            {
                Action = reader.GetString(reader.GetOrdinal("action")),
                CapabilityPk = reader.IsDBNull(reader.GetOrdinal("capability_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("capability_pk")),
                VersionPk = reader.IsDBNull(reader.GetOrdinal("version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("version_pk")),
                DefinitionPk = reader.IsDBNull(reader.GetOrdinal("definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("definition_pk")),
                Digest = reader.IsDBNull(reader.GetOrdinal("digest")) ? (string?)null : reader.GetString(reader.GetOrdinal("digest"))
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

