//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareEstatePatternCorrespondence.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class ModelDeclareEstatePatternCorrespondenceRepository : IModelDeclareEstatePatternCorrespondenceRepository
    {
        private readonly string _connectionString;

        public ModelDeclareEstatePatternCorrespondenceRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<object?>> ExecuteAsync(string correspondenceId, string estateForm, string kernelPattern, string compilerDecision, string status, string evidenceRefs, string contested, string scope, string mappingVersion)
        {
            var entities = new List<object?>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_estate_pattern_correspondence]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@correspondence_id", correspondenceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_form", estateForm ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@kernel_pattern", kernelPattern ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@compiler_decision", compilerDecision ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@status", status ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@evidence_refs", evidenceRefs ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@contested", contested ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@scope", scope ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@mapping_version", mappingVersion ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            // This procedure does not return a result set.
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_estate_pattern_correspondence: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<object?> Execute(string correspondenceId, string estateForm, string kernelPattern, string compilerDecision, string status, string evidenceRefs, string contested, string scope, string mappingVersion)
        {
            var entities = new List<object?>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_estate_pattern_correspondence]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@correspondence_id", correspondenceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@estate_form", estateForm ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@kernel_pattern", kernelPattern ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@compiler_decision", compilerDecision ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@status", status ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@evidence_refs", evidenceRefs ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@contested", contested ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@scope", scope ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@mapping_version", mappingVersion ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            // This procedure does not return a result set.
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_estate_pattern_correspondence: " + ex.Message, ex);
            }
        }
        
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

