//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareCapabilityDocument.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class ModelDeclareCapabilityDocumentRepository : IModelDeclareCapabilityDocumentRepository
    {
        private readonly string _connectionString;

        public ModelDeclareCapabilityDocumentRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<object?>> ExecuteAsync(string document, string onUnchanged)
        {
            var entities = new List<object?>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_capability_document]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@document", document ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@on_unchanged", onUnchanged ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            // This procedure does not return a result set.
                        }
                        while (await reader.NextResultAsync())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_capability_document: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<object?> Execute(string document, string onUnchanged)
        {
            var entities = new List<object?>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_capability_document]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@document", document ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@on_unchanged", onUnchanged ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            // This procedure does not return a result set.
                        }
                        while (reader.NextResult())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_capability_document: " + ex.Message, ex);
            }
        }
        
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

