//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelDeclareCapabilityFeature.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class ModelDeclareCapabilityFeatureRepository : IModelDeclareCapabilityFeatureRepository
    {
        private readonly string _connectionString;

        public ModelDeclareCapabilityFeatureRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, string featureText)
        {
            var entities = new List<object?>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_capability_feature]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@feature_text", featureText ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (await reader.NextResultAsync() == false)
                            {
                                break;
                            }
                        }
                    }
                    // This procedure does not return a result set.
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_capability_feature: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<object?> Execute(string capabilityId, string featureText)
        {
            var entities = new List<object?>();
            var resultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[declare_capability_feature]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@feature_text", featureText ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (true)
                        {
                            if (reader.FieldCount > 0)
                            {
                                // DataTable.Load consumes the current result set and advances past it,
                                // so do not call NextResult here or alternating sets are skipped. It may
                                // also close the reader once the last set is consumed.
                                var resultSet = new DataTable();
                                resultSet.Load(reader);
                                resultSets.Add(resultSet);
                                if (reader.IsClosed)
                                {
                                    break;
                                }
                                continue;
                            }
                            if (reader.NextResult() == false)
                            {
                                break;
                            }
                        }
                    }
                    // This procedure does not return a result set.
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        ResultSets = resultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.declare_capability_feature: " + ex.Message, ex);
            }
        }
        
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

