//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelSetDefinitionLabel.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class ModelSetDefinitionLabelRepository : IModelSetDefinitionLabelRepository
    {
        private readonly string _connectionString;

        public ModelSetDefinitionLabelRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<ModelSetDefinitionLabel>> ExecuteAsync(string namespaceId, string declaredId, string versionLabel, string objectKind, long semanticObjectDefinitionPk)
        {
            var entities = new List<ModelSetDefinitionLabel>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[set_definition_label]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@namespace_id", namespaceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@declared_id", declaredId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@version_label", versionLabel ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@object_kind", objectKind ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@semantic_object_definition_pk", semanticObjectDefinitionPk);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToModelSetDefinitionLabel(reader));
                        }
                        while (await reader.NextResultAsync())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<ModelSetDefinitionLabel>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.set_definition_label: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<ModelSetDefinitionLabel> Execute(string namespaceId, string declaredId, string versionLabel, string objectKind, long semanticObjectDefinitionPk)
        {
            var entities = new List<ModelSetDefinitionLabel>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[set_definition_label]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@namespace_id", namespaceId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@declared_id", declaredId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@version_label", versionLabel ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@object_kind", objectKind ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@semantic_object_definition_pk", semanticObjectDefinitionPk);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToModelSetDefinitionLabel(reader));
                        }
                        while (reader.NextResult())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<ModelSetDefinitionLabel>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.set_definition_label: " + ex.Message, ex);
            }
        }
        
        public ModelSetDefinitionLabel MapReaderToModelSetDefinitionLabel(SqlDataReader reader)
        {
            return new ModelSetDefinitionLabel
            {
                Action = reader.GetString(reader.GetOrdinal("action")),
                Disposition = reader.GetString(reader.GetOrdinal("disposition")),
                NamespaceId = reader.IsDBNull(reader.GetOrdinal("namespace_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("namespace_id")),
                DeclaredId = reader.IsDBNull(reader.GetOrdinal("declared_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("declared_id")),
                ObjectKind = reader.IsDBNull(reader.GetOrdinal("object_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("object_kind")),
                SemanticObjectPk = reader.IsDBNull(reader.GetOrdinal("semantic_object_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("semantic_object_pk")),
                SemanticObjectDefinitionPk = reader.IsDBNull(reader.GetOrdinal("semantic_object_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("semantic_object_definition_pk")),
                VersionLabel = reader.IsDBNull(reader.GetOrdinal("version_label")) ? (string?)null : reader.GetString(reader.GetOrdinal("version_label"))
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

