//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelConfigureContract.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Repositories
{
    public partial class ModelConfigureContractRepository : IModelConfigureContractRepository
    {
        private readonly string _connectionString;

        public ModelConfigureContractRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<ModelConfigureContract>> ExecuteAsync(string capabilityId, string face, string addPropertiesJson, string removePropertiesJson, bool required)
        {
            var entities = new List<ModelConfigureContract>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_contract]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@face", face ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@add_properties_json", addPropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@remove_properties_json", removePropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@required", required);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToModelConfigureContract(reader));
                        }
                        while (await reader.NextResultAsync())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureContract>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_contract: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<ModelConfigureContract> Execute(string capabilityId, string face, string addPropertiesJson, string removePropertiesJson, bool required)
        {
            var entities = new List<ModelConfigureContract>();
            var additionalResultSets = new List<DataTable>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[configure_contract]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@face", face ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@add_properties_json", addPropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@remove_properties_json", removePropertiesJson ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@required", required);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToModelConfigureContract(reader));
                        }
                        while (reader.NextResult())
                        {
                            var additionalResultSet = new DataTable();
                            additionalResultSet.Load(reader);
                            additionalResultSets.Add(additionalResultSet);
                        }
                    }
                    return new ProcedureCallResult<ModelConfigureContract>
                    {
                        Rows = entities,
                        AdditionalResultSets = additionalResultSets,
                        OutputParameters = GetOutputParameters(command)
                    };         
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.configure_contract: " + ex.Message, ex);
            }
        }
        
        public ModelConfigureContract MapReaderToModelConfigureContract(SqlDataReader reader)
        {
            return new ModelConfigureContract
            {
                Action = reader.GetString(reader.GetOrdinal("action")),
                CapabilityId = reader.IsDBNull(reader.GetOrdinal("capability_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("capability_id")),
                Face = reader.IsDBNull(reader.GetOrdinal("face")) ? (string?)null : reader.GetString(reader.GetOrdinal("face")),
                ContractVersionBefore = reader.IsDBNull(reader.GetOrdinal("contract_version_before")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("contract_version_before")),
                ContractVersionAfter = reader.IsDBNull(reader.GetOrdinal("contract_version_after")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("contract_version_after")),
                PayloadPropertiesBefore = reader.IsDBNull(reader.GetOrdinal("payload_properties_before")) ? (string?)null : reader.GetString(reader.GetOrdinal("payload_properties_before")),
                PayloadPropertiesAfter = reader.IsDBNull(reader.GetOrdinal("payload_properties_after")) ? (string?)null : reader.GetString(reader.GetOrdinal("payload_properties_after"))
            };
        }
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

