//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ModelRemoveMechanic.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class ModelRemoveMechanicRepository : IModelRemoveMechanicRepository
    {
        private readonly string _connectionString;

        public ModelRemoveMechanicRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<ProcedureCallResult<object?>> ExecuteAsync(string capabilityId, string outputField)
        {
            var entities = new List<object?>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[remove_mechanic]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@output_field", outputField ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            // This procedure does not return a result set.
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.remove_mechanic: " + ex.Message, ex);
            }
        }
        
        public ProcedureCallResult<object?> Execute(string capabilityId, string outputField)
        {
            var entities = new List<object?>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand("[model].[remove_mechanic]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@capability_id", capabilityId ?? (object)DBNull.Value);
                    command.Parameters.AddWithValue("@output_field", outputField ?? (object)DBNull.Value);
                    
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            // This procedure does not return a result set.
                        }
                    }
                    return new ProcedureCallResult<object?>
                    {
                        Rows = entities,
                        OutputParameters = GetOutputParameters(command)
                    };
                }
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing procedure model.remove_mechanic: " + ex.Message, ex);
            }
        }
        
        
        private static IReadOnlyDictionary<string, object?> GetOutputParameters(SqlCommand command)
        {
            var outputParameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
            foreach (SqlParameter parameter in command.Parameters)
            {
                if (parameter.Direction == ParameterDirection.Output || parameter.Direction == ParameterDirection.InputOutput)
                {
                    outputParameters[parameter.ParameterName.TrimStart('@')] = parameter.Value == DBNull.Value ? null : parameter.Value;
                }
            }
            return outputParameters;
        }
    }
}

