//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;

namespace SFX.DAL.Operations
{
    /// <summary>
    /// The outcome of a declared writer operation: the token values captured from the
    /// verification read before and after the writer call, the rows the verification
    /// read returned after the writer call, and the writer output parameter values.
    /// </summary>
    public sealed class OperationResult
    {
        /// <summary>The first token value captured before the writer call, when one was read.</summary>
        public string? BeforeToken { get; init; }

        /// <summary>The first token value captured after the writer call, when one was read.</summary>
        public string? AfterToken { get; init; }

        /// <summary>True when ApplyAsync compared the expected token against the verification read.</summary>
        public bool TokenChecked { get; init; }

        /// <summary>The rows returned by the verification read after the writer call completed.</summary>
        public IReadOnlyList<IReadOnlyDictionary<string, object?>> Rows { get; init; } = Array.Empty<IReadOnlyDictionary<string, object?>>();

        /// <summary>The output parameter values returned by the writer, keyed by parameter name.</summary>
        public IReadOnlyDictionary<string, object?> OutputParameters { get; init; } = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
    }
}
