//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'VCapabilityFixtureOwnerDrift.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class VCapabilityFixtureOwnerDrift
    {
        public string CapabilityId { get; set; } = default!;
        public long CurrentCapabilityDefinitionPk { get; set; }
        public string FixtureId { get; set; } = default!;
        public long StaleOwnerDefinitionPk { get; set; }
    }
}