//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'VScenarioEmbodimentReadiness.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class VScenarioEmbodimentReadiness
    {
        public long? AccountedRequirementCount { get; set; }
        public string CapabilityId { get; set; } = default!;
        public long CapabilityVersionPk { get; set; }
        public string? ConformanceStatus { get; set; }
        public long EstateModelPk { get; set; }
        public long? OpenRequirementCount { get; set; }
        public string Readiness { get; set; } = default!;
        public long? RequirementCount { get; set; }
        public string ScenarioId { get; set; } = default!;
        public long SelectedScenarioVersionPk { get; set; }
        public string? TargetLanguage { get; set; }
    }
}