//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'VCapabilityExecutionDeclaration.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IVCapabilityExecutionDeclarationRepository : IReadOnlyRepository<VCapabilityExecutionDeclaration>
    {

        VCapabilityExecutionDeclaration? GetById(string capabilityId, string entryId);
        Task<VCapabilityExecutionDeclaration?> GetByIdAsync(string capabilityId, string entryId);


    }
}

