//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'RunCaptureIssue.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.Identity.DAL.Helpers;
using SFX.Identity.DAL.Models;

namespace SFX.Identity.DAL.Interfaces
{
    public partial interface IRunCaptureIssueRepository : IRepository<RunCaptureIssue>
    {

        Task<List<RunCaptureIssue>> GetByRunIdAsync(string id);

        List<RunCaptureIssue> GetByRunId(string id);

    }
}

