//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AssessmentDefinitionInput.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAssessmentDefinitionInputRepository : IRepository<AssessmentDefinitionInput>
    {

        AssessmentDefinitionInput? GetById(long assessmentPk, long semanticObjectDefinitionPk, string role);
        Task<AssessmentDefinitionInput?> GetByIdAsync(long assessmentPk, long semanticObjectDefinitionPk, string role);
        Task<List<AssessmentDefinitionInput>> GetByAssessmentPkAsync(long id);
        Task<List<AssessmentDefinitionInput>> GetBySemanticObjectDefinitionPkAsync(long id);

        List<AssessmentDefinitionInput> GetByAssessmentPk(long id);
        List<AssessmentDefinitionInput> GetBySemanticObjectDefinitionPk(long id);

    }
}

