//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Authority.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAuthorityRepository : IRepository<Authority>
    {

        Task<List<Authority>> GetByAuthorityIdAsync(string id);
        Task<List<Authority>> GetByNamespacePkAsync(long id);
        Task<List<Authority>> GetByObjectKindAsync(string id);
        Task<List<Authority>> GetBySemanticObjectPkAsync(long id);

        List<Authority> GetByAuthorityId(string id);
        List<Authority> GetByNamespacePk(long id);
        List<Authority> GetByObjectKind(string id);
        List<Authority> GetBySemanticObjectPk(long id);

    }
}

