//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'BlueprintObservedTransitionMapping.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IBlueprintObservedTransitionMappingRepository : IRepository<BlueprintObservedTransitionMapping>
    {

        BlueprintObservedTransitionMapping? GetById(long estateModelPk, long blueprintEdgePk, long sourceObservationPk, long mappingAuthorityDefinitionPk);
        Task<BlueprintObservedTransitionMapping?> GetByIdAsync(long estateModelPk, long blueprintEdgePk, long sourceObservationPk, long mappingAuthorityDefinitionPk);
        Task<List<BlueprintObservedTransitionMapping>> GetByBlueprintEdgePkAsync(long id);
        Task<List<BlueprintObservedTransitionMapping>> GetByEstateModelPkAsync(long id);
        Task<List<BlueprintObservedTransitionMapping>> GetByMappingAuthorityDefinitionPkAsync(long id);
        Task<List<BlueprintObservedTransitionMapping>> GetBySourceObservationPkAsync(long id);

        List<BlueprintObservedTransitionMapping> GetByBlueprintEdgePk(long id);
        List<BlueprintObservedTransitionMapping> GetByEstateModelPk(long id);
        List<BlueprintObservedTransitionMapping> GetByMappingAuthorityDefinitionPk(long id);
        List<BlueprintObservedTransitionMapping> GetBySourceObservationPk(long id);

    }
}

