//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EstateCapability.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IEstateCapabilityRepository : IRepository<EstateCapability>
    {

        EstateCapability? GetById(long estateModelPk, long capabilityPk);
        Task<EstateCapability?> GetByIdAsync(long estateModelPk, long capabilityPk);
        Task<List<EstateCapability>> GetByCapabilityPkAsync(long id);
        Task<List<EstateCapability>> GetByCapabilityVersionPkAsync(long id);
        Task<List<EstateCapability>> GetByEstateModelPkAsync(long id);
        Task<List<EstateCapability>> GetBySemanticObjectDefinitionPkAsync(long id);

        List<EstateCapability> GetByCapabilityPk(long id);
        List<EstateCapability> GetByCapabilityVersionPk(long id);
        List<EstateCapability> GetByEstateModelPk(long id);
        List<EstateCapability> GetBySemanticObjectDefinitionPk(long id);

    }
}

