//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EstateScenarioFaceResolution.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IEstateScenarioFaceResolutionRepository : IRepository<EstateScenarioFaceResolution>
    {

        EstateScenarioFaceResolution? GetById(long estateModelPk, long scenarioVersionPk, string role);
        Task<EstateScenarioFaceResolution?> GetByIdAsync(long estateModelPk, long scenarioVersionPk, string role);
        Task<List<EstateScenarioFaceResolution>> GetByContractVersionPkAsync(long id);
        Task<List<EstateScenarioFaceResolution>> GetByEstateModelPkAsync(long id);
        Task<List<EstateScenarioFaceResolution>> GetByExecutionAuthorityVersionPkAsync(long id);
        Task<List<EstateScenarioFaceResolution>> GetByScenarioVersionPkAsync(long id);

        List<EstateScenarioFaceResolution> GetByContractVersionPk(long id);
        List<EstateScenarioFaceResolution> GetByEstateModelPk(long id);
        List<EstateScenarioFaceResolution> GetByExecutionAuthorityVersionPk(long id);
        List<EstateScenarioFaceResolution> GetByScenarioVersionPk(long id);

    }
}

