//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ExpressionSemanticReference.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IExpressionSemanticReferenceRepository : IRepository<ExpressionSemanticReference>
    {

        Task<List<ExpressionSemanticReference>> GetByOwnerDefinitionPkAsync(long id);
        Task<List<ExpressionSemanticReference>> GetByExpectedKindAsync(string id);
        Task<List<ExpressionSemanticReference>> GetByExpressionNodePkAsync(long id);
        Task<List<ExpressionSemanticReference>> GetBySemanticObjectDefinitionPkAsync(long id);

        List<ExpressionSemanticReference> GetByOwnerDefinitionPk(long id);
        List<ExpressionSemanticReference> GetByExpectedKind(string id);
        List<ExpressionSemanticReference> GetByExpressionNodePk(long id);
        List<ExpressionSemanticReference> GetBySemanticObjectDefinitionPk(long id);

    }
}

