//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'GenerationRequest.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IGenerationRequestRepository : IRepository<GenerationRequest>
    {

        Task<List<GenerationRequest>> GetByRequestBlobDigestAsync(byte[] id);
        Task<List<GenerationRequest>> GetByRequirementIdAsync(long id);

        List<GenerationRequest> GetByRequestBlobDigest(byte[] id);
        List<GenerationRequest> GetByRequirementId(long id);

    }
}

