//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'IntegrityFinding.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IIntegrityFindingRepository : IRepository<IntegrityFinding>
    {

        Task<List<IntegrityFinding>> GetByAssessmentPkAsync(long id);
        Task<List<IntegrityFinding>> GetByExpectedContentPkAsync(long id);
        Task<List<IntegrityFinding>> GetByObservedContentPkAsync(long id);
        Task<List<IntegrityFinding>> GetBySourceObservationPkAsync(long id);
        Task<List<IntegrityFinding>> GetBySubjectDefinitionPkAsync(long id);

        List<IntegrityFinding> GetByAssessmentPk(long id);
        List<IntegrityFinding> GetByExpectedContentPk(long id);
        List<IntegrityFinding> GetByObservedContentPk(long id);
        List<IntegrityFinding> GetBySourceObservationPk(long id);
        List<IntegrityFinding> GetBySubjectDefinitionPk(long id);

    }
}

