//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'OperationScenarioInvocation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IOperationScenarioInvocationRepository : IRepository<OperationScenarioInvocation>
    {

        Task<List<OperationScenarioInvocation>> GetByOwnerDefinitionPkAsync(long id);
        Task<List<OperationScenarioInvocation>> GetByExecutionOperationPkAsync(long id);
        Task<List<OperationScenarioInvocation>> GetByOperationKindAsync(string id);
        Task<List<OperationScenarioInvocation>> GetByTargetScenarioVersionPkAsync(long id);

        List<OperationScenarioInvocation> GetByOwnerDefinitionPk(long id);
        List<OperationScenarioInvocation> GetByExecutionOperationPk(long id);
        List<OperationScenarioInvocation> GetByOperationKind(string id);
        List<OperationScenarioInvocation> GetByTargetScenarioVersionPk(long id);

    }
}

