//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'OperationTransformation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IOperationTransformationRepository : IRepository<OperationTransformation>
    {

        OperationTransformation? GetById(long executionOperationPk, long transformationVersionPk, string role);
        Task<OperationTransformation?> GetByIdAsync(long executionOperationPk, long transformationVersionPk, string role);
        Task<List<OperationTransformation>> GetByOwnerDefinitionPkAsync(long id);
        Task<List<OperationTransformation>> GetByExecutionOperationPkAsync(long id);
        Task<List<OperationTransformation>> GetByTransformationVersionPkAsync(long id);

        List<OperationTransformation> GetByOwnerDefinitionPk(long id);
        List<OperationTransformation> GetByExecutionOperationPk(long id);
        List<OperationTransformation> GetByTransformationVersionPk(long id);

    }
}

