//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'PortContract.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IPortContractRepository : IRepository<PortContract>
    {

        PortContract? GetById(long portVersionPk, string direction, int memberOrdinal);
        Task<PortContract?> GetByIdAsync(long portVersionPk, string direction, int memberOrdinal);
        Task<List<PortContract>> GetByOwnerDefinitionPkAsync(long id);
        Task<List<PortContract>> GetByContractVersionPkAsync(long id);
        Task<List<PortContract>> GetByPortVersionPkAsync(long id);

        List<PortContract> GetByOwnerDefinitionPk(long id);
        List<PortContract> GetByContractVersionPk(long id);
        List<PortContract> GetByPortVersionPk(long id);

    }
}

