//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Product.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IProductRepository : IRepository<Product>
    {

        Task<List<Product>> GetByNamespacePkAsync(long id);
        Task<List<Product>> GetByObjectKindAsync(string id);
        Task<List<Product>> GetByProductIdAsync(string id);
        Task<List<Product>> GetBySemanticObjectPkAsync(long id);

        List<Product> GetByNamespacePk(long id);
        List<Product> GetByObjectKind(string id);
        List<Product> GetByProductId(string id);
        List<Product> GetBySemanticObjectPk(long id);

    }
}

