//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Transformation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface ITransformationRepository : IRepository<Transformation>
    {

        Task<List<Transformation>> GetByNamespacePkAsync(long id);
        Task<List<Transformation>> GetByObjectKindAsync(string id);
        Task<List<Transformation>> GetBySemanticObjectPkAsync(long id);
        Task<List<Transformation>> GetByTransformationIdAsync(string id);

        List<Transformation> GetByNamespacePk(long id);
        List<Transformation> GetByObjectKind(string id);
        List<Transformation> GetBySemanticObjectPk(long id);
        List<Transformation> GetByTransformationId(string id);

    }
}

