//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'TransformationExpressionNode.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface ITransformationExpressionNodeRepository : IRepository<TransformationExpressionNode>
    {

        Task<List<TransformationExpressionNode>> GetByOwnerDefinitionPkAsync(long id);
        Task<List<TransformationExpressionNode>> GetByLiteralContentPkAsync(long id);
        Task<List<TransformationExpressionNode>> GetByTransformationVersionPkAsync(long id);

        List<TransformationExpressionNode> GetByOwnerDefinitionPk(long id);
        List<TransformationExpressionNode> GetByLiteralContentPk(long id);
        List<TransformationExpressionNode> GetByTransformationVersionPk(long id);

    }
}

