//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFnContractSchemaClosure.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisFnContractSchemaClosureRepository
    {
        List<AnalysisFnContractSchemaClosure> Execute(long contentPk);
        Task<List<AnalysisFnContractSchemaClosure>> ExecuteAsync(long contentPk);

        List<AnalysisFnContractSchemaClosure> GetAny(QueryDetail<AnalysisFnContractSchemaClosure> queryDetail, long contentPk);
        Task<List<AnalysisFnContractSchemaClosure>> GetAnyAsync(QueryDetail<AnalysisFnContractSchemaClosure> queryDetail, long contentPk);
    }
}
