//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvContractSatisfiability.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisFvContractSatisfiabilityRepository
    {
        List<AnalysisFvContractSatisfiability> Execute(long estateModelPk);
        Task<List<AnalysisFvContractSatisfiability>> ExecuteAsync(long estateModelPk);

        List<AnalysisFvContractSatisfiability> GetAny(QueryDetail<AnalysisFvContractSatisfiability> queryDetail, long estateModelPk);
        Task<List<AnalysisFvContractSatisfiability>> GetAnyAsync(QueryDetail<AnalysisFvContractSatisfiability> queryDetail, long estateModelPk);
    }
}
