//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvWitnesses.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IAnalysisFvWitnessesRepository
    {
        List<AnalysisFvWitnesses> Execute(long estateModelPk);
        Task<List<AnalysisFvWitnesses>> ExecuteAsync(long estateModelPk);

        List<AnalysisFvWitnesses> GetAny(QueryDetail<AnalysisFvWitnesses> queryDetail, long estateModelPk);
        Task<List<AnalysisFvWitnesses>> GetAnyAsync(QueryDetail<AnalysisFvWitnesses> queryDetail, long estateModelPk);
    }
}
