//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeReachTransformations.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IProbeReachTransformationsRepository
    {
        List<ProbeReachTransformations> Execute(long estateModelPk, string capabilityId);
        Task<List<ProbeReachTransformations>> ExecuteAsync(long estateModelPk, string capabilityId);

        List<ProbeReachTransformations> GetAny(QueryDetail<ProbeReachTransformations> queryDetail, long estateModelPk, string capabilityId);
        Task<List<ProbeReachTransformations>> GetAnyAsync(QueryDetail<ProbeReachTransformations> queryDetail, long estateModelPk, string capabilityId);
    }
}
