//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeInstallAdmission.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IProbeInstallAdmissionRepository
    {
        List<ProbeInstallAdmission> Execute(long estateModelPk, long portVersionPk);
        Task<List<ProbeInstallAdmission>> ExecuteAsync(long estateModelPk, long portVersionPk);

        List<ProbeInstallAdmission> GetAny(QueryDetail<ProbeInstallAdmission> queryDetail, long estateModelPk, long portVersionPk);
        Task<List<ProbeInstallAdmission>> GetAnyAsync(QueryDetail<ProbeInstallAdmission> queryDetail, long estateModelPk, long portVersionPk);
    }
}
