//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeCurrentModelPin.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using SFX.DAL.Helpers;
using SFX.DAL.Models;

namespace SFX.DAL.Interfaces
{
    public partial interface IProbeCurrentModelPinRepository
    {
        List<ProbeCurrentModelPin> Execute();
        Task<List<ProbeCurrentModelPin>> ExecuteAsync();

        List<ProbeCurrentModelPin> GetAny(QueryDetail<ProbeCurrentModelPin> queryDetail);
        Task<List<ProbeCurrentModelPin>> GetAnyAsync(QueryDetail<ProbeCurrentModelPin> queryDetail);
    }
}
