//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'VDeclaredPlatformImplementation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class VDeclaredPlatformImplementationRepository : IVDeclaredPlatformImplementationRepository
    {
        private readonly string _connectionString;

        public VDeclaredPlatformImplementationRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<VDeclaredPlatformImplementation?> GetByIdAsync(long capabilityVersionPk, string platformCapabilityId, long providerDefinitionPk)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_declared_platform_implementation]   WHERE [capability_version_pk] = @CapabilityVersionPk AND [platform_capability_id] = @PlatformCapabilityId AND [provider_definition_pk] = @ProviderDefinitionPk", connection))
                {
                    command.Parameters.AddWithValue("@CapabilityVersionPk", capabilityVersionPk);
                    command.Parameters.AddWithValue("@PlatformCapabilityId", platformCapabilityId);
                    command.Parameters.AddWithValue("@ProviderDefinitionPk", providerDefinitionPk);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        if (reader.Read())
                        {
                            return await MapReaderToVDeclaredPlatformImplementationAsync(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public VDeclaredPlatformImplementation? GetById(long capabilityVersionPk, string platformCapabilityId, long providerDefinitionPk)
        {
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_declared_platform_implementation]   WHERE [capability_version_pk] = @CapabilityVersionPk AND [platform_capability_id] = @PlatformCapabilityId AND [provider_definition_pk] = @ProviderDefinitionPk", connection))
                {
                    command.Parameters.AddWithValue("@CapabilityVersionPk", capabilityVersionPk);
                    command.Parameters.AddWithValue("@PlatformCapabilityId", platformCapabilityId);
                    command.Parameters.AddWithValue("@ProviderDefinitionPk", providerDefinitionPk);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapReaderToVDeclaredPlatformImplementation(reader);
                        }
                    }
                }
                return null;  // If no record is found
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entity from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<VDeclaredPlatformImplementation>> GetAllAsync()
        {
            var entities = new List<VDeclaredPlatformImplementation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_declared_platform_implementation]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToVDeclaredPlatformImplementationAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<VDeclaredPlatformImplementation>> GetAnyAsync(QueryDetail<VDeclaredPlatformImplementation> queryDetail)
        {
            var entities = new List<VDeclaredPlatformImplementation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<VDeclaredPlatformImplementation>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToVDeclaredPlatformImplementationAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<VDeclaredPlatformImplementation> GetAll()
        {
            var entities = new List<VDeclaredPlatformImplementation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_declared_platform_implementation]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToVDeclaredPlatformImplementation(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<VDeclaredPlatformImplementation> GetAny(QueryDetail<VDeclaredPlatformImplementation> queryDetail)
        {
            var entities = new List<VDeclaredPlatformImplementation>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<VDeclaredPlatformImplementation>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToVDeclaredPlatformImplementation(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<VDeclaredPlatformImplementation> MapReaderToVDeclaredPlatformImplementationAsync(SqlDataReader reader)
        {
            return new VDeclaredPlatformImplementation
            {
                CapabilityDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("capability_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("capability_definition_pk")),
                CapabilityVersionPk = await reader.IsDBNullAsync(reader.GetOrdinal("capability_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("capability_version_pk")),
                ConformanceRef = await reader.IsDBNullAsync(reader.GetOrdinal("conformance_ref")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_ref")),
                DeclarationStatus = await reader.IsDBNullAsync(reader.GetOrdinal("declaration_status")) ? (string?)null : reader.GetString(reader.GetOrdinal("declaration_status")),
                EstateModelPk = await reader.IsDBNullAsync(reader.GetOrdinal("estate_model_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                ImplementationId = await reader.IsDBNullAsync(reader.GetOrdinal("implementation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_id")),
                PlatformCapabilityId = await reader.IsDBNullAsync(reader.GetOrdinal("platform_capability_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("platform_capability_id")),
                PlatformDefinitionDigest = await reader.IsDBNullAsync(reader.GetOrdinal("platform_definition_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("platform_definition_digest")),
                ProviderDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("provider_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("provider_definition_pk")),
                ProviderId = await reader.IsDBNullAsync(reader.GetOrdinal("provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_id")),
                TargetLanguage = await reader.IsDBNullAsync(reader.GetOrdinal("target_language")) ? (string?)null : reader.GetString(reader.GetOrdinal("target_language"))
            };
        }
        
        public VDeclaredPlatformImplementation MapReaderToVDeclaredPlatformImplementation(SqlDataReader reader)
        {
            return new VDeclaredPlatformImplementation
            {
                CapabilityDefinitionPk = reader.IsDBNull(reader.GetOrdinal("capability_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("capability_definition_pk")),
                CapabilityVersionPk = reader.IsDBNull(reader.GetOrdinal("capability_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("capability_version_pk")),
                ConformanceRef = reader.IsDBNull(reader.GetOrdinal("conformance_ref")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_ref")),
                DeclarationStatus = reader.IsDBNull(reader.GetOrdinal("declaration_status")) ? (string?)null : reader.GetString(reader.GetOrdinal("declaration_status")),
                EstateModelPk = reader.IsDBNull(reader.GetOrdinal("estate_model_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                ImplementationId = reader.IsDBNull(reader.GetOrdinal("implementation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_id")),
                PlatformCapabilityId = reader.IsDBNull(reader.GetOrdinal("platform_capability_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("platform_capability_id")),
                PlatformDefinitionDigest = reader.IsDBNull(reader.GetOrdinal("platform_definition_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("platform_definition_digest")),
                ProviderDefinitionPk = reader.IsDBNull(reader.GetOrdinal("provider_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("provider_definition_pk")),
                ProviderId = reader.IsDBNull(reader.GetOrdinal("provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_id")),
                TargetLanguage = reader.IsDBNull(reader.GetOrdinal("target_language")) ? (string?)null : reader.GetString(reader.GetOrdinal("target_language"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CapabilityDefinitionPk", "capability_definition_pk" },
            { "CapabilityVersionPk", "capability_version_pk" },
            { "ConformanceRef", "conformance_ref" },
            { "DeclarationStatus", "declaration_status" },
            { "EstateModelPk", "estate_model_pk" },
            { "ImplementationId", "implementation_id" },
            { "PlatformCapabilityId", "platform_capability_id" },
            { "PlatformDefinitionDigest", "platform_definition_digest" },
            { "ProviderDefinitionPk", "provider_definition_pk" },
            { "ProviderId", "provider_id" },
            { "TargetLanguage", "target_language" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<VDeclaredPlatformImplementation> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<VDeclaredPlatformImplementation>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<VDeclaredPlatformImplementation>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY capability_version_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[v_declared_platform_implementation]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public VDeclaredPlatformImplementation? GetById(object id)
        {
            throw new NotSupportedException("Table [analysis].[v_declared_platform_implementation] has a composite primary key (long, string, long). Use the typed GetById overload instead.");
        }

        public Task<VDeclaredPlatformImplementation?> GetByIdAsync(object id)
        {
            throw new NotSupportedException("Table [analysis].[v_declared_platform_implementation] has a composite primary key (long, string, long). Use the typed GetByIdAsync overload instead.");
        }
    }
}

