//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'VScenarioLanguageResolution.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class VScenarioLanguageResolutionRepository : IVScenarioLanguageResolutionRepository
    {
        private readonly string _connectionString;

        public VScenarioLanguageResolutionRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public VScenarioLanguageResolution? GetById(object id)
        {
            throw new NotSupportedException("View [analysis].[v_scenario_language_resolution] has no configured KeyColumns. Use GetAll or GetAny instead.");
        }

        public Task<VScenarioLanguageResolution?> GetByIdAsync(object id)
        {
            throw new NotSupportedException("View [analysis].[v_scenario_language_resolution] has no configured KeyColumns. Use GetAllAsync or GetAnyAsync instead.");
        }
        
        public async Task<IEnumerable<VScenarioLanguageResolution>> GetAllAsync()
        {
            var entities = new List<VScenarioLanguageResolution>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_scenario_language_resolution]  ", connection))
                {
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToVScenarioLanguageResolutionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<IEnumerable<VScenarioLanguageResolution>> GetAnyAsync(QueryDetail<VScenarioLanguageResolution> queryDetail)
        {
            var entities = new List<VScenarioLanguageResolution>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<VScenarioLanguageResolution>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (reader.Read())
                        {
                            entities.Add(await MapReaderToVScenarioLanguageResolutionAsync(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<VScenarioLanguageResolution> GetAll()
        {
            var entities = new List<VScenarioLanguageResolution>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[v_scenario_language_resolution]  ", connection))
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToVScenarioLanguageResolution(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public IEnumerable<VScenarioLanguageResolution> GetAny(QueryDetail<VScenarioLanguageResolution> queryDetail)
        {
            var entities = new List<VScenarioLanguageResolution>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    QueryDetail<VScenarioLanguageResolution>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToVScenarioLanguageResolution(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error retrieving entities from the database: " + ex.Message, ex);
            }
        }
        
        public async Task<VScenarioLanguageResolution> MapReaderToVScenarioLanguageResolutionAsync(SqlDataReader reader)
        {
            return new VScenarioLanguageResolution
            {
                Altitude = await reader.IsDBNullAsync(reader.GetOrdinal("altitude")) ? (string?)null : reader.GetString(reader.GetOrdinal("altitude")),
                BaseDiagnostic = reader.GetString(reader.GetOrdinal("base_diagnostic")),
                BaseResolutionStatus = reader.GetString(reader.GetOrdinal("base_resolution_status")),
                CapabilityId = reader.GetString(reader.GetOrdinal("capability_id")),
                CapabilityVersionPk = reader.GetInt64(reader.GetOrdinal("capability_version_pk")),
                ConformanceRef = await reader.IsDBNullAsync(reader.GetOrdinal("conformance_ref")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_ref")),
                ConformanceStatus = await reader.IsDBNullAsync(reader.GetOrdinal("conformance_status")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_status")),
                CycleDetected = await reader.IsDBNullAsync(reader.GetOrdinal("cycle_detected")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("cycle_detected")),
                DeclaredAuthorityDigest = await reader.IsDBNullAsync(reader.GetOrdinal("declared_authority_digest")) ? (string?)null : reader.GetString(reader.GetOrdinal("declared_authority_digest")),
                Diagnostic = reader.GetString(reader.GetOrdinal("diagnostic")),
                DownstreamScenarioId = reader.GetString(reader.GetOrdinal("downstream_scenario_id")),
                DownstreamScenarioVersionPk = await reader.IsDBNullAsync(reader.GetOrdinal("downstream_scenario_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("downstream_scenario_version_pk")),
                EstateModelPk = reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                ExecutionOperationPk = await reader.IsDBNullAsync(reader.GetOrdinal("execution_operation_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("execution_operation_pk")),
                ImplementationEvidenceState = await reader.IsDBNullAsync(reader.GetOrdinal("implementation_evidence_state")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_evidence_state")),
                ImplementationExport = await reader.IsDBNullAsync(reader.GetOrdinal("implementation_export")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_export")),
                ImplementationId = await reader.IsDBNullAsync(reader.GetOrdinal("implementation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_id")),
                MechanicSourceDigest = await reader.IsDBNullAsync(reader.GetOrdinal("mechanic_source_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("mechanic_source_digest")),
                MinimumDepth = await reader.IsDBNullAsync(reader.GetOrdinal("minimum_depth")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("minimum_depth")),
                PortVersionPk = await reader.IsDBNullAsync(reader.GetOrdinal("port_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_version_pk")),
                ProfileDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("profile_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("profile_definition_pk")),
                ProvenanceClass = await reader.IsDBNullAsync(reader.GetOrdinal("provenance_class")) ? (string?)null : reader.GetString(reader.GetOrdinal("provenance_class")),
                ProviderDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("provider_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("provider_definition_pk")),
                ProviderId = await reader.IsDBNullAsync(reader.GetOrdinal("provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_id")),
                ProviderProfileId = await reader.IsDBNullAsync(reader.GetOrdinal("provider_profile_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_profile_id")),
                RegistrySourceDigest = await reader.IsDBNullAsync(reader.GetOrdinal("registry_source_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("registry_source_digest")),
                RepairBoundary = await reader.IsDBNullAsync(reader.GetOrdinal("repair_boundary")) ? (string?)null : reader.GetString(reader.GetOrdinal("repair_boundary")),
                RequirementDefinitionDigest = await reader.IsDBNullAsync(reader.GetOrdinal("requirement_definition_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("requirement_definition_digest")),
                RequirementDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("requirement_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("requirement_definition_pk")),
                RequirementId = await reader.IsDBNullAsync(reader.GetOrdinal("requirement_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_id")),
                RequirementKind = await reader.IsDBNullAsync(reader.GetOrdinal("requirement_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_kind")),
                RequirementUse = await reader.IsDBNullAsync(reader.GetOrdinal("requirement_use")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_use")),
                ResolutionCandidateCount = await reader.IsDBNullAsync(reader.GetOrdinal("resolution_candidate_count")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("resolution_candidate_count")),
                ResolutionStatus = reader.GetString(reader.GetOrdinal("resolution_status")),
                ResolverId = await reader.IsDBNullAsync(reader.GetOrdinal("resolver_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("resolver_id")),
                ScenarioDefinitionDigest = (byte[])reader.GetValue(reader.GetOrdinal("scenario_definition_digest")),
                ScenarioId = reader.GetString(reader.GetOrdinal("scenario_id")),
                SelectedScenarioVersionPk = reader.GetInt64(reader.GetOrdinal("selected_scenario_version_pk")),
                SourceDefinitionPk = await reader.IsDBNullAsync(reader.GetOrdinal("source_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("source_definition_pk")),
                SourcePointer = await reader.IsDBNullAsync(reader.GetOrdinal("source_pointer")) ? (string?)null : reader.GetString(reader.GetOrdinal("source_pointer")),
                TargetLanguage = await reader.IsDBNullAsync(reader.GetOrdinal("target_language")) ? (string?)null : reader.GetString(reader.GetOrdinal("target_language")),
                TransformationVersionPk = await reader.IsDBNullAsync(reader.GetOrdinal("transformation_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("transformation_version_pk"))
            };
        }
        
        public VScenarioLanguageResolution MapReaderToVScenarioLanguageResolution(SqlDataReader reader)
        {
            return new VScenarioLanguageResolution
            {
                Altitude = reader.IsDBNull(reader.GetOrdinal("altitude")) ? (string?)null : reader.GetString(reader.GetOrdinal("altitude")),
                BaseDiagnostic = reader.GetString(reader.GetOrdinal("base_diagnostic")),
                BaseResolutionStatus = reader.GetString(reader.GetOrdinal("base_resolution_status")),
                CapabilityId = reader.GetString(reader.GetOrdinal("capability_id")),
                CapabilityVersionPk = reader.GetInt64(reader.GetOrdinal("capability_version_pk")),
                ConformanceRef = reader.IsDBNull(reader.GetOrdinal("conformance_ref")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_ref")),
                ConformanceStatus = reader.IsDBNull(reader.GetOrdinal("conformance_status")) ? (string?)null : reader.GetString(reader.GetOrdinal("conformance_status")),
                CycleDetected = reader.IsDBNull(reader.GetOrdinal("cycle_detected")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("cycle_detected")),
                DeclaredAuthorityDigest = reader.IsDBNull(reader.GetOrdinal("declared_authority_digest")) ? (string?)null : reader.GetString(reader.GetOrdinal("declared_authority_digest")),
                Diagnostic = reader.GetString(reader.GetOrdinal("diagnostic")),
                DownstreamScenarioId = reader.GetString(reader.GetOrdinal("downstream_scenario_id")),
                DownstreamScenarioVersionPk = reader.IsDBNull(reader.GetOrdinal("downstream_scenario_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("downstream_scenario_version_pk")),
                EstateModelPk = reader.GetInt64(reader.GetOrdinal("estate_model_pk")),
                ExecutionOperationPk = reader.IsDBNull(reader.GetOrdinal("execution_operation_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("execution_operation_pk")),
                ImplementationEvidenceState = reader.IsDBNull(reader.GetOrdinal("implementation_evidence_state")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_evidence_state")),
                ImplementationExport = reader.IsDBNull(reader.GetOrdinal("implementation_export")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_export")),
                ImplementationId = reader.IsDBNull(reader.GetOrdinal("implementation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("implementation_id")),
                MechanicSourceDigest = reader.IsDBNull(reader.GetOrdinal("mechanic_source_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("mechanic_source_digest")),
                MinimumDepth = reader.IsDBNull(reader.GetOrdinal("minimum_depth")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("minimum_depth")),
                PortVersionPk = reader.IsDBNull(reader.GetOrdinal("port_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_version_pk")),
                ProfileDefinitionPk = reader.IsDBNull(reader.GetOrdinal("profile_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("profile_definition_pk")),
                ProvenanceClass = reader.IsDBNull(reader.GetOrdinal("provenance_class")) ? (string?)null : reader.GetString(reader.GetOrdinal("provenance_class")),
                ProviderDefinitionPk = reader.IsDBNull(reader.GetOrdinal("provider_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("provider_definition_pk")),
                ProviderId = reader.IsDBNull(reader.GetOrdinal("provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_id")),
                ProviderProfileId = reader.IsDBNull(reader.GetOrdinal("provider_profile_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_profile_id")),
                RegistrySourceDigest = reader.IsDBNull(reader.GetOrdinal("registry_source_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("registry_source_digest")),
                RepairBoundary = reader.IsDBNull(reader.GetOrdinal("repair_boundary")) ? (string?)null : reader.GetString(reader.GetOrdinal("repair_boundary")),
                RequirementDefinitionDigest = reader.IsDBNull(reader.GetOrdinal("requirement_definition_digest")) ? (byte[]?)null : (byte[])reader.GetValue(reader.GetOrdinal("requirement_definition_digest")),
                RequirementDefinitionPk = reader.IsDBNull(reader.GetOrdinal("requirement_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("requirement_definition_pk")),
                RequirementId = reader.IsDBNull(reader.GetOrdinal("requirement_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_id")),
                RequirementKind = reader.IsDBNull(reader.GetOrdinal("requirement_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_kind")),
                RequirementUse = reader.IsDBNull(reader.GetOrdinal("requirement_use")) ? (string?)null : reader.GetString(reader.GetOrdinal("requirement_use")),
                ResolutionCandidateCount = reader.IsDBNull(reader.GetOrdinal("resolution_candidate_count")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("resolution_candidate_count")),
                ResolutionStatus = reader.GetString(reader.GetOrdinal("resolution_status")),
                ResolverId = reader.IsDBNull(reader.GetOrdinal("resolver_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("resolver_id")),
                ScenarioDefinitionDigest = (byte[])reader.GetValue(reader.GetOrdinal("scenario_definition_digest")),
                ScenarioId = reader.GetString(reader.GetOrdinal("scenario_id")),
                SelectedScenarioVersionPk = reader.GetInt64(reader.GetOrdinal("selected_scenario_version_pk")),
                SourceDefinitionPk = reader.IsDBNull(reader.GetOrdinal("source_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("source_definition_pk")),
                SourcePointer = reader.IsDBNull(reader.GetOrdinal("source_pointer")) ? (string?)null : reader.GetString(reader.GetOrdinal("source_pointer")),
                TargetLanguage = reader.IsDBNull(reader.GetOrdinal("target_language")) ? (string?)null : reader.GetString(reader.GetOrdinal("target_language")),
                TransformationVersionPk = reader.IsDBNull(reader.GetOrdinal("transformation_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("transformation_version_pk"))
            };
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Altitude", "altitude" },
            { "BaseDiagnostic", "base_diagnostic" },
            { "BaseResolutionStatus", "base_resolution_status" },
            { "CapabilityId", "capability_id" },
            { "CapabilityVersionPk", "capability_version_pk" },
            { "ConformanceRef", "conformance_ref" },
            { "ConformanceStatus", "conformance_status" },
            { "CycleDetected", "cycle_detected" },
            { "DeclaredAuthorityDigest", "declared_authority_digest" },
            { "Diagnostic", "diagnostic" },
            { "DownstreamScenarioId", "downstream_scenario_id" },
            { "DownstreamScenarioVersionPk", "downstream_scenario_version_pk" },
            { "EstateModelPk", "estate_model_pk" },
            { "ExecutionOperationPk", "execution_operation_pk" },
            { "ImplementationEvidenceState", "implementation_evidence_state" },
            { "ImplementationExport", "implementation_export" },
            { "ImplementationId", "implementation_id" },
            { "MechanicSourceDigest", "mechanic_source_digest" },
            { "MinimumDepth", "minimum_depth" },
            { "PortVersionPk", "port_version_pk" },
            { "ProfileDefinitionPk", "profile_definition_pk" },
            { "ProvenanceClass", "provenance_class" },
            { "ProviderDefinitionPk", "provider_definition_pk" },
            { "ProviderId", "provider_id" },
            { "ProviderProfileId", "provider_profile_id" },
            { "RegistrySourceDigest", "registry_source_digest" },
            { "RepairBoundary", "repair_boundary" },
            { "RequirementDefinitionDigest", "requirement_definition_digest" },
            { "RequirementDefinitionPk", "requirement_definition_pk" },
            { "RequirementId", "requirement_id" },
            { "RequirementKind", "requirement_kind" },
            { "RequirementUse", "requirement_use" },
            { "ResolutionCandidateCount", "resolution_candidate_count" },
            { "ResolutionStatus", "resolution_status" },
            { "ResolverId", "resolver_id" },
            { "ScenarioDefinitionDigest", "scenario_definition_digest" },
            { "ScenarioId", "scenario_id" },
            { "SelectedScenarioVersionPk", "selected_scenario_version_pk" },
            { "SourceDefinitionPk", "source_definition_pk" },
            { "SourcePointer", "source_pointer" },
            { "TargetLanguage", "target_language" },
            { "TransformationVersionPk", "transformation_version_pk" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<VScenarioLanguageResolution> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<VScenarioLanguageResolution>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<VScenarioLanguageResolution>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY altitude";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[v_scenario_language_resolution]  ) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
    }
}

