//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvContractFaceCompatibility.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisFvContractFaceCompatibilityRepository : IAnalysisFvContractFaceCompatibilityRepository
    {
        private readonly string _connectionString;

        public AnalysisFvContractFaceCompatibilityRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<List<AnalysisFvContractFaceCompatibility>> ExecuteAsync(long estateModelPk)
        {
            var entities = new List<AnalysisFvContractFaceCompatibility>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_contract_face_compatibility](@estateModelPk)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvContractFaceCompatibility(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_contract_face_compatibility: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvContractFaceCompatibility> Execute(long estateModelPk)
        {
            var entities = new List<AnalysisFvContractFaceCompatibility>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_contract_face_compatibility](@estateModelPk)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvContractFaceCompatibility(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_contract_face_compatibility: " + ex.Message, ex);
            }
        }
        
        public async Task<List<AnalysisFvContractFaceCompatibility>> GetAnyAsync(QueryDetail<AnalysisFvContractFaceCompatibility> queryDetail, long estateModelPk)
        {
            var entities = new List<AnalysisFvContractFaceCompatibility>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    QueryDetail<AnalysisFvContractFaceCompatibility>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvContractFaceCompatibility(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_contract_face_compatibility: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvContractFaceCompatibility> GetAny(QueryDetail<AnalysisFvContractFaceCompatibility> queryDetail, long estateModelPk)
        {
            var entities = new List<AnalysisFvContractFaceCompatibility>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    QueryDetail<AnalysisFvContractFaceCompatibility>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvContractFaceCompatibility(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_contract_face_compatibility: " + ex.Message, ex);
            }
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CapabilityId", "capability_id" },
            { "EdgeKind", "edge_kind" },
            { "FromScenario", "from_scenario" },
            { "ToScenario", "to_scenario" },
            { "FromContract", "from_contract" },
            { "ToContract", "to_contract" },
            { "IdentityHolds", "identity_holds" },
            { "Disposition", "disposition" },
            { "Basis", "basis" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<AnalysisFvContractFaceCompatibility> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<AnalysisFvContractFaceCompatibility>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<AnalysisFvContractFaceCompatibility>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY capability_id";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[fv_contract_face_compatibility](@estateModelPk)) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public AnalysisFvContractFaceCompatibility MapReaderToAnalysisFvContractFaceCompatibility(SqlDataReader reader)
        {
            return new AnalysisFvContractFaceCompatibility
            {
                CapabilityId = reader.GetString(reader.GetOrdinal("capability_id")),
                EdgeKind = reader.GetString(reader.GetOrdinal("edge_kind")),
                FromScenario = reader.IsDBNull(reader.GetOrdinal("from_scenario")) ? (string?)null : reader.GetString(reader.GetOrdinal("from_scenario")),
                ToScenario = reader.IsDBNull(reader.GetOrdinal("to_scenario")) ? (string?)null : reader.GetString(reader.GetOrdinal("to_scenario")),
                FromContract = reader.IsDBNull(reader.GetOrdinal("from_contract")) ? (string?)null : reader.GetString(reader.GetOrdinal("from_contract")),
                ToContract = reader.IsDBNull(reader.GetOrdinal("to_contract")) ? (string?)null : reader.GetString(reader.GetOrdinal("to_contract")),
                IdentityHolds = reader.GetInt32(reader.GetOrdinal("identity_holds")),
                Disposition = reader.GetString(reader.GetOrdinal("disposition")),
                Basis = reader.IsDBNull(reader.GetOrdinal("basis")) ? (string?)null : reader.GetString(reader.GetOrdinal("basis"))
            };
        }
    }
}

