//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvCapabilityTopologyConformance.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisFvCapabilityTopologyConformanceRepository : IAnalysisFvCapabilityTopologyConformanceRepository
    {
        private readonly string _connectionString;

        public AnalysisFvCapabilityTopologyConformanceRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<List<AnalysisFvCapabilityTopologyConformance>> ExecuteAsync(long estateModelPk, string capabilityId)
        {
            var entities = new List<AnalysisFvCapabilityTopologyConformance>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_capability_topology_conformance](@estateModelPk, @capabilityId)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@capabilityId", capabilityId);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvCapabilityTopologyConformance(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_capability_topology_conformance: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvCapabilityTopologyConformance> Execute(long estateModelPk, string capabilityId)
        {
            var entities = new List<AnalysisFvCapabilityTopologyConformance>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_capability_topology_conformance](@estateModelPk, @capabilityId)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@capabilityId", capabilityId);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvCapabilityTopologyConformance(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_capability_topology_conformance: " + ex.Message, ex);
            }
        }
        
        public async Task<List<AnalysisFvCapabilityTopologyConformance>> GetAnyAsync(QueryDetail<AnalysisFvCapabilityTopologyConformance> queryDetail, long estateModelPk, string capabilityId)
        {
            var entities = new List<AnalysisFvCapabilityTopologyConformance>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@capabilityId", capabilityId);
                    QueryDetail<AnalysisFvCapabilityTopologyConformance>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvCapabilityTopologyConformance(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_capability_topology_conformance: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvCapabilityTopologyConformance> GetAny(QueryDetail<AnalysisFvCapabilityTopologyConformance> queryDetail, long estateModelPk, string capabilityId)
        {
            var entities = new List<AnalysisFvCapabilityTopologyConformance>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@capabilityId", capabilityId);
                    QueryDetail<AnalysisFvCapabilityTopologyConformance>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvCapabilityTopologyConformance(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_capability_topology_conformance: " + ex.Message, ex);
            }
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CapabilityId", "capability_id" },
            { "NamespaceId", "namespace_id" },
            { "CapabilityPk", "capability_pk" },
            { "Depth", "depth" },
            { "ExecutionAuthorityVersionPk", "execution_authority_version_pk" },
            { "AuthoritySod", "authority_sod" },
            { "AuthorityIsNewestSelected", "authority_is_newest_selected" },
            { "AuthorityBoundSelected", "authority_bound_selected" },
            { "ExecutionOperationPk", "execution_operation_pk" },
            { "Ordinal", "ordinal" },
            { "OperationId", "operation_id" },
            { "OperationKind", "operation_kind" },
            { "OperationBound", "operation_bound" },
            { "InvocationTargetResolved", "invocation_target_resolved" },
            { "TargetScenarioVersionPk", "target_scenario_version_pk" },
            { "PortPk", "port_pk" },
            { "PortId", "port_id" },
            { "PortVersionPk", "port_version_pk" },
            { "PortSod", "port_sod" },
            { "PortSelected", "port_selected" },
            { "LinkedIsNewest", "linked_is_newest" },
            { "SupplierClass", "supplier_class" },
            { "ExplicitProviderId", "explicit_provider_id" },
            { "NestedProviderId", "nested_provider_id" },
            { "SupplierIdentity", "supplier_identity" },
            { "SupplierIdentityPresent", "supplier_identity_present" },
            { "SupplierIdentityUses", "supplier_identity_uses" },
            { "SupplierRouteDuplicate", "supplier_route_duplicate" },
            { "ProviderLabel", "provider_label" },
            { "ProviderLabelPresent", "provider_label_present" },
            { "CapabilityLabel", "capability_label" },
            { "CapabilityLabelPresent", "capability_label_present" },
            { "ResidueRouteNodes", "residue_route_nodes" },
            { "TypedOnlyNodes", "typed_only_nodes" },
            { "ResidueScanSkipped", "residue_scan_skipped" },
            { "SupplierScanSkipped", "supplier_scan_skipped" },
            { "NamespacePorts", "namespace_ports" },
            { "UnlinkedCapabilityPorts", "unlinked_capability_ports" },
            { "SlotsWithoutBinding", "slots_without_binding" },
            { "SlotsWithoutSelectedOperation", "slots_without_selected_operation" },
            { "UnboundSelectedAuthorities", "unbound_selected_authorities" },
            { "ReachTruncatedEdges", "reach_truncated_edges" },
            { "CanonicalOperations", "canonical_operations" },
            { "BoundOperations", "bound_operations" },
            { "CanonicalUnboundDetail", "canonical_unbound_detail" },
            { "RequestNamedDispatch", "request_named_dispatch" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<AnalysisFvCapabilityTopologyConformance> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<AnalysisFvCapabilityTopologyConformance>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<AnalysisFvCapabilityTopologyConformance>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY capability_id";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[fv_capability_topology_conformance](@estateModelPk, @capabilityId)) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public AnalysisFvCapabilityTopologyConformance MapReaderToAnalysisFvCapabilityTopologyConformance(SqlDataReader reader)
        {
            return new AnalysisFvCapabilityTopologyConformance
            {
                CapabilityId = reader.GetString(reader.GetOrdinal("capability_id")),
                NamespaceId = reader.GetString(reader.GetOrdinal("namespace_id")),
                CapabilityPk = reader.GetInt64(reader.GetOrdinal("capability_pk")),
                Depth = reader.IsDBNull(reader.GetOrdinal("depth")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("depth")),
                ExecutionAuthorityVersionPk = reader.IsDBNull(reader.GetOrdinal("execution_authority_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("execution_authority_version_pk")),
                AuthoritySod = reader.GetInt64(reader.GetOrdinal("authority_sod")),
                AuthorityIsNewestSelected = reader.IsDBNull(reader.GetOrdinal("authority_is_newest_selected")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("authority_is_newest_selected")),
                AuthorityBoundSelected = reader.IsDBNull(reader.GetOrdinal("authority_bound_selected")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("authority_bound_selected")),
                ExecutionOperationPk = reader.GetInt64(reader.GetOrdinal("execution_operation_pk")),
                Ordinal = reader.GetInt32(reader.GetOrdinal("ordinal")),
                OperationId = reader.IsDBNull(reader.GetOrdinal("operation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("operation_id")),
                OperationKind = reader.GetString(reader.GetOrdinal("operation_kind")),
                OperationBound = reader.IsDBNull(reader.GetOrdinal("operation_bound")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("operation_bound")),
                InvocationTargetResolved = reader.IsDBNull(reader.GetOrdinal("invocation_target_resolved")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("invocation_target_resolved")),
                TargetScenarioVersionPk = reader.IsDBNull(reader.GetOrdinal("target_scenario_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("target_scenario_version_pk")),
                PortPk = reader.IsDBNull(reader.GetOrdinal("port_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_pk")),
                PortId = reader.IsDBNull(reader.GetOrdinal("port_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("port_id")),
                PortVersionPk = reader.IsDBNull(reader.GetOrdinal("port_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_version_pk")),
                PortSod = reader.IsDBNull(reader.GetOrdinal("port_sod")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_sod")),
                PortSelected = reader.IsDBNull(reader.GetOrdinal("port_selected")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("port_selected")),
                LinkedIsNewest = reader.IsDBNull(reader.GetOrdinal("linked_is_newest")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("linked_is_newest")),
                SupplierClass = reader.IsDBNull(reader.GetOrdinal("supplier_class")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("supplier_class")),
                ExplicitProviderId = reader.IsDBNull(reader.GetOrdinal("explicit_provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("explicit_provider_id")),
                NestedProviderId = reader.IsDBNull(reader.GetOrdinal("nested_provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("nested_provider_id")),
                SupplierIdentity = reader.IsDBNull(reader.GetOrdinal("supplier_identity")) ? (string?)null : reader.GetString(reader.GetOrdinal("supplier_identity")),
                SupplierIdentityPresent = reader.IsDBNull(reader.GetOrdinal("supplier_identity_present")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("supplier_identity_present")),
                SupplierIdentityUses = reader.GetInt32(reader.GetOrdinal("supplier_identity_uses")),
                SupplierRouteDuplicate = reader.IsDBNull(reader.GetOrdinal("supplier_route_duplicate")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("supplier_route_duplicate")),
                ProviderLabel = reader.IsDBNull(reader.GetOrdinal("provider_label")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_label")),
                ProviderLabelPresent = reader.IsDBNull(reader.GetOrdinal("provider_label_present")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("provider_label_present")),
                CapabilityLabel = reader.IsDBNull(reader.GetOrdinal("capability_label")) ? (string?)null : reader.GetString(reader.GetOrdinal("capability_label")),
                CapabilityLabelPresent = reader.IsDBNull(reader.GetOrdinal("capability_label_present")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("capability_label_present")),
                ResidueRouteNodes = reader.GetInt32(reader.GetOrdinal("residue_route_nodes")),
                TypedOnlyNodes = reader.GetInt32(reader.GetOrdinal("typed_only_nodes")),
                ResidueScanSkipped = reader.GetInt32(reader.GetOrdinal("residue_scan_skipped")),
                SupplierScanSkipped = reader.GetBoolean(reader.GetOrdinal("supplier_scan_skipped")),
                NamespacePorts = reader.GetInt32(reader.GetOrdinal("namespace_ports")),
                UnlinkedCapabilityPorts = reader.GetInt32(reader.GetOrdinal("unlinked_capability_ports")),
                SlotsWithoutBinding = reader.GetInt32(reader.GetOrdinal("slots_without_binding")),
                SlotsWithoutSelectedOperation = reader.GetInt32(reader.GetOrdinal("slots_without_selected_operation")),
                UnboundSelectedAuthorities = reader.GetInt32(reader.GetOrdinal("unbound_selected_authorities")),
                ReachTruncatedEdges = reader.IsDBNull(reader.GetOrdinal("reach_truncated_edges")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("reach_truncated_edges")),
                CanonicalOperations = reader.GetInt32(reader.GetOrdinal("canonical_operations")),
                BoundOperations = reader.GetInt32(reader.GetOrdinal("bound_operations")),
                CanonicalUnboundDetail = reader.IsDBNull(reader.GetOrdinal("canonical_unbound_detail")) ? (string?)null : reader.GetString(reader.GetOrdinal("canonical_unbound_detail")),
                RequestNamedDispatch = reader.IsDBNull(reader.GetOrdinal("request_named_dispatch")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("request_named_dispatch"))
            };
        }
    }
}

