//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisScenarioTransformationMechanics.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisScenarioTransformationMechanicsRepository : IAnalysisScenarioTransformationMechanicsRepository
    {
        private readonly string _connectionString;

        public AnalysisScenarioTransformationMechanicsRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<List<AnalysisScenarioTransformationMechanics>> ExecuteAsync(long transformationVersionPk)
        {
            var entities = new List<AnalysisScenarioTransformationMechanics>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[scenario_transformation_mechanics](@transformationVersionPk)", connection))
                {
                    command.Parameters.AddWithValue("@transformationVersionPk", transformationVersionPk);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisScenarioTransformationMechanics(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.scenario_transformation_mechanics: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisScenarioTransformationMechanics> Execute(long transformationVersionPk)
        {
            var entities = new List<AnalysisScenarioTransformationMechanics>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[scenario_transformation_mechanics](@transformationVersionPk)", connection))
                {
                    command.Parameters.AddWithValue("@transformationVersionPk", transformationVersionPk);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisScenarioTransformationMechanics(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.scenario_transformation_mechanics: " + ex.Message, ex);
            }
        }
        
        public async Task<List<AnalysisScenarioTransformationMechanics>> GetAnyAsync(QueryDetail<AnalysisScenarioTransformationMechanics> queryDetail, long transformationVersionPk)
        {
            var entities = new List<AnalysisScenarioTransformationMechanics>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@transformationVersionPk", transformationVersionPk);
                    QueryDetail<AnalysisScenarioTransformationMechanics>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisScenarioTransformationMechanics(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.scenario_transformation_mechanics: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisScenarioTransformationMechanics> GetAny(QueryDetail<AnalysisScenarioTransformationMechanics> queryDetail, long transformationVersionPk)
        {
            var entities = new List<AnalysisScenarioTransformationMechanics>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@transformationVersionPk", transformationVersionPk);
                    QueryDetail<AnalysisScenarioTransformationMechanics>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisScenarioTransformationMechanics(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.scenario_transformation_mechanics: " + ex.Message, ex);
            }
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "TransformationVersionPk", "transformation_version_pk" },
            { "ExpressionNodePk", "expression_node_pk" },
            { "NodePointer", "node_pointer" },
            { "OperationName", "operation_name" },
            { "MechanicDefinitionPk", "mechanic_definition_pk" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<AnalysisScenarioTransformationMechanics> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<AnalysisScenarioTransformationMechanics>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<AnalysisScenarioTransformationMechanics>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY transformation_version_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[scenario_transformation_mechanics](@transformationVersionPk)) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public AnalysisScenarioTransformationMechanics MapReaderToAnalysisScenarioTransformationMechanics(SqlDataReader reader)
        {
            return new AnalysisScenarioTransformationMechanics
            {
                TransformationVersionPk = reader.IsDBNull(reader.GetOrdinal("transformation_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("transformation_version_pk")),
                ExpressionNodePk = reader.IsDBNull(reader.GetOrdinal("expression_node_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("expression_node_pk")),
                NodePointer = reader.IsDBNull(reader.GetOrdinal("node_pointer")) ? (string?)null : reader.GetString(reader.GetOrdinal("node_pointer")),
                OperationName = reader.IsDBNull(reader.GetOrdinal("operation_name")) ? (string?)null : reader.GetString(reader.GetOrdinal("operation_name")),
                MechanicDefinitionPk = reader.IsDBNull(reader.GetOrdinal("mechanic_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("mechanic_definition_pk"))
            };
        }
    }
}

