//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AnalysisFvProviderReferenceEvidence.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class AnalysisFvProviderReferenceEvidenceRepository : IAnalysisFvProviderReferenceEvidenceRepository
    {
        private readonly string _connectionString;

        public AnalysisFvProviderReferenceEvidenceRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<List<AnalysisFvProviderReferenceEvidence>> ExecuteAsync(long estateModelPk)
        {
            var entities = new List<AnalysisFvProviderReferenceEvidence>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_provider_reference_evidence](@estateModelPk)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvProviderReferenceEvidence(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_provider_reference_evidence: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvProviderReferenceEvidence> Execute(long estateModelPk)
        {
            var entities = new List<AnalysisFvProviderReferenceEvidence>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [analysis].[fv_provider_reference_evidence](@estateModelPk)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvProviderReferenceEvidence(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_provider_reference_evidence: " + ex.Message, ex);
            }
        }
        
        public async Task<List<AnalysisFvProviderReferenceEvidence>> GetAnyAsync(QueryDetail<AnalysisFvProviderReferenceEvidence> queryDetail, long estateModelPk)
        {
            var entities = new List<AnalysisFvProviderReferenceEvidence>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    QueryDetail<AnalysisFvProviderReferenceEvidence>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToAnalysisFvProviderReferenceEvidence(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_provider_reference_evidence: " + ex.Message, ex);
            }
        }
        
        public List<AnalysisFvProviderReferenceEvidence> GetAny(QueryDetail<AnalysisFvProviderReferenceEvidence> queryDetail, long estateModelPk)
        {
            var entities = new List<AnalysisFvProviderReferenceEvidence>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    QueryDetail<AnalysisFvProviderReferenceEvidence>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToAnalysisFvProviderReferenceEvidence(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function analysis.fv_provider_reference_evidence: " + ex.Message, ex);
            }
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CapabilityId", "capability_id" },
            { "CapabilityNamespace", "capability_namespace" },
            { "ScenarioId", "scenario_id" },
            { "ExecutionAuthorityVersionPk", "execution_authority_version_pk" },
            { "ExecutionOperationPk", "execution_operation_pk" },
            { "Ordinal", "ordinal" },
            { "OperationId", "operation_id" },
            { "PortVersionPk", "port_version_pk" },
            { "PortPk", "port_pk" },
            { "PortId", "port_id" },
            { "PlatformCapabilityId", "platform_capability_id" },
            { "ProviderId", "provider_id" },
            { "ReferenceKind", "reference_kind" },
            { "ProviderAuthorityId", "provider_authority_id" },
            { "BindingId", "binding_id" },
            { "EndpointAuthorityDigest", "endpoint_authority_digest" },
            { "ApplicationRef", "application_ref" },
            { "ProviderReferenceResolved", "provider_reference_resolved" },
            { "BindingReferenceResolved", "binding_reference_resolved" },
            { "EndpointAuthorityResolved", "endpoint_authority_resolved" },
            { "ApplicationReferenceResolved", "application_reference_resolved" },
            { "ReferenceClosureSatisfied", "reference_closure_satisfied" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<AnalysisFvProviderReferenceEvidence> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<AnalysisFvProviderReferenceEvidence>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<AnalysisFvProviderReferenceEvidence>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY capability_id";

            return $@"SELECT e.* FROM (SELECT * FROM [analysis].[fv_provider_reference_evidence](@estateModelPk)) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public AnalysisFvProviderReferenceEvidence MapReaderToAnalysisFvProviderReferenceEvidence(SqlDataReader reader)
        {
            return new AnalysisFvProviderReferenceEvidence
            {
                CapabilityId = reader.GetString(reader.GetOrdinal("capability_id")),
                CapabilityNamespace = reader.IsDBNull(reader.GetOrdinal("capability_namespace")) ? (string?)null : reader.GetString(reader.GetOrdinal("capability_namespace")),
                ScenarioId = reader.GetString(reader.GetOrdinal("scenario_id")),
                ExecutionAuthorityVersionPk = reader.IsDBNull(reader.GetOrdinal("execution_authority_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("execution_authority_version_pk")),
                ExecutionOperationPk = reader.GetInt64(reader.GetOrdinal("execution_operation_pk")),
                Ordinal = reader.GetInt32(reader.GetOrdinal("ordinal")),
                OperationId = reader.IsDBNull(reader.GetOrdinal("operation_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("operation_id")),
                PortVersionPk = reader.GetInt64(reader.GetOrdinal("port_version_pk")),
                PortPk = reader.GetInt64(reader.GetOrdinal("port_pk")),
                PortId = reader.GetString(reader.GetOrdinal("port_id")),
                PlatformCapabilityId = reader.IsDBNull(reader.GetOrdinal("platform_capability_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("platform_capability_id")),
                ProviderId = reader.IsDBNull(reader.GetOrdinal("provider_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_id")),
                ReferenceKind = reader.GetString(reader.GetOrdinal("reference_kind")),
                ProviderAuthorityId = reader.IsDBNull(reader.GetOrdinal("provider_authority_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("provider_authority_id")),
                BindingId = reader.IsDBNull(reader.GetOrdinal("binding_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("binding_id")),
                EndpointAuthorityDigest = reader.IsDBNull(reader.GetOrdinal("endpoint_authority_digest")) ? (string?)null : reader.GetString(reader.GetOrdinal("endpoint_authority_digest")),
                ApplicationRef = reader.IsDBNull(reader.GetOrdinal("application_ref")) ? (string?)null : reader.GetString(reader.GetOrdinal("application_ref")),
                ProviderReferenceResolved = reader.IsDBNull(reader.GetOrdinal("provider_reference_resolved")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("provider_reference_resolved")),
                BindingReferenceResolved = reader.IsDBNull(reader.GetOrdinal("binding_reference_resolved")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("binding_reference_resolved")),
                EndpointAuthorityResolved = reader.IsDBNull(reader.GetOrdinal("endpoint_authority_resolved")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("endpoint_authority_resolved")),
                ApplicationReferenceResolved = reader.IsDBNull(reader.GetOrdinal("application_reference_resolved")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("application_reference_resolved")),
                ReferenceClosureSatisfied = reader.IsDBNull(reader.GetOrdinal("reference_closure_satisfied")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal("reference_closure_satisfied"))
            };
        }
    }
}

