//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProbeBlueprint.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using SFX.DAL.Interfaces;
using SFX.DAL.Models;
using SFX.DAL.Helpers;

namespace SFX.DAL.Repositories
{
    public partial class ProbeBlueprintRepository : IProbeBlueprintRepository
    {
        private readonly string _connectionString;

        public ProbeBlueprintRepository()
        {
            _connectionString = DatabaseHelper.GetConnectionString();
        }
        
        public async Task<List<ProbeBlueprint>> ExecuteAsync(long estateModelPk, string namespaceId, string blueprintId)
        {
            var entities = new List<ProbeBlueprint>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [probe].[blueprint](@estateModelPk, @namespaceId, @blueprintId)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@namespaceId", namespaceId);
                    command.Parameters.AddWithValue("@blueprintId", blueprintId);
                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToProbeBlueprint(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function probe.blueprint: " + ex.Message, ex);
            }
        }
        
        public List<ProbeBlueprint> Execute(long estateModelPk, string namespaceId, string blueprintId)
        {
            var entities = new List<ProbeBlueprint>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(@"SELECT * FROM [probe].[blueprint](@estateModelPk, @namespaceId, @blueprintId)", connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@namespaceId", namespaceId);
                    command.Parameters.AddWithValue("@blueprintId", blueprintId);
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToProbeBlueprint(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function probe.blueprint: " + ex.Message, ex);
            }
        }
        
        public async Task<List<ProbeBlueprint>> GetAnyAsync(QueryDetail<ProbeBlueprint> queryDetail, long estateModelPk, string namespaceId, string blueprintId)
        {
            var entities = new List<ProbeBlueprint>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@namespaceId", namespaceId);
                    command.Parameters.AddWithValue("@blueprintId", blueprintId);
                    QueryDetail<ProbeBlueprint>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            entities.Add(MapReaderToProbeBlueprint(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function probe.blueprint: " + ex.Message, ex);
            }
        }
        
        public List<ProbeBlueprint> GetAny(QueryDetail<ProbeBlueprint> queryDetail, long estateModelPk, string namespaceId, string blueprintId)
        {
            var entities = new List<ProbeBlueprint>();
            try
            {
                using (var connection = new SqlConnection(_connectionString))
                using (var command = new SqlCommand(BuildSqlQuery(queryDetail), connection))
                {
                    command.Parameters.AddWithValue("@estateModelPk", estateModelPk);
                    command.Parameters.AddWithValue("@namespaceId", namespaceId);
                    command.Parameters.AddWithValue("@blueprintId", blueprintId);
                    QueryDetail<ProbeBlueprint>.AddSearchParameters(command, queryDetail.SearchCriteria);
                    command.Parameters.AddWithValue("@Offset", (queryDetail.Page - 1) * queryDetail.PageSize);
                    command.Parameters.AddWithValue("@PageSize", queryDetail.PageSize);

                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            entities.Add(MapReaderToProbeBlueprint(reader));
                        }
                    }
                }
                return entities;
            }
            catch (SqlException ex)
            {
                throw new ApplicationException("Error executing function probe.blueprint: " + ex.Message, ex);
            }
        }
        
        private static readonly Dictionary<string, string> _columnNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "BlueprintPk", "blueprint_pk" },
            { "BlueprintId", "blueprint_id" },
            { "BlueprintVersionPk", "blueprint_version_pk" },
            { "BlueprintDefinitionDigest", "blueprint_definition_digest" },
            { "CapabilityPk", "capability_pk" },
            { "CapabilityVersionPk", "capability_version_pk" },
            { "CarrierProfile", "carrier_profile" },
            { "SourceDisposition", "source_disposition" },
            { "BlueprintNodePk", "blueprint_node_pk" },
            { "NodeId", "node_id" },
            { "NodeKind", "node_kind" },
            { "Altitude", "altitude" },
            { "ProjectionOrdinal", "projection_ordinal" },
            { "NodePortDefinitionPk", "node_port_definition_pk" },
            { "ExpectedSemanticKind", "expected_semantic_kind" },
            { "ProviderSlotPk", "provider_slot_pk" },
            { "SlotId", "slot_id" },
            { "SlotPortRequirementPk", "slot_port_requirement_pk" },
            { "PortVersionPk", "port_version_pk" },
            { "RequirementOrdinal", "requirement_ordinal" },
            { "Role", "role" },
        };

        private static string GetColumnName(string propertyName)
        {
            return _columnNames.TryGetValue(propertyName, out var columnName) ? columnName : propertyName;
        }

        private string BuildSqlQuery(QueryDetail<ProbeBlueprint> queryDetail)
        {
            var whereClauses = new List<string>();
            int index = 0;
            foreach (var criteria in queryDetail.SearchCriteria)
            {
                string columnName = GetColumnName(criteria.GetColumnName());
                if (criteria.TrimSpaces) columnName = $"TRIM({columnName})";
                string sqlOperator = QueryDetail<ProbeBlueprint>.GetSqlOperator(criteria.Operator);
                whereClauses.Add($"{columnName} {sqlOperator} @{criteria.GetColumnName()}{index}");
                index++;
            }

            string whereClause = whereClauses.Any() ? "WHERE " + string.Join(" AND ", whereClauses) : string.Empty;

            var orderByClauses = new List<string>();
            foreach (var orderBy in queryDetail.OrderByList)
            {
                orderByClauses.Add($"{GetColumnName(orderBy.GetColumnName())} {QueryDetail<ProbeBlueprint>.GetSqlDirection(orderBy.Direction)}");
            }

            string orderByClause = orderByClauses.Any() ? "ORDER BY " + string.Join(", ", orderByClauses) : "ORDER BY blueprint_pk";

            return $@"SELECT e.* FROM (SELECT * FROM [probe].[blueprint](@estateModelPk, @namespaceId, @blueprintId)) e {whereClause} {orderByClause}
                  OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY";
        }
        
        public ProbeBlueprint MapReaderToProbeBlueprint(SqlDataReader reader)
        {
            return new ProbeBlueprint
            {
                BlueprintPk = reader.GetInt64(reader.GetOrdinal("blueprint_pk")),
                BlueprintId = reader.GetString(reader.GetOrdinal("blueprint_id")),
                BlueprintVersionPk = reader.GetInt64(reader.GetOrdinal("blueprint_version_pk")),
                BlueprintDefinitionDigest = (byte[])reader.GetValue(reader.GetOrdinal("blueprint_definition_digest")),
                CapabilityPk = reader.GetInt64(reader.GetOrdinal("capability_pk")),
                CapabilityVersionPk = reader.GetInt64(reader.GetOrdinal("capability_version_pk")),
                CarrierProfile = reader.GetString(reader.GetOrdinal("carrier_profile")),
                SourceDisposition = reader.GetString(reader.GetOrdinal("source_disposition")),
                BlueprintNodePk = reader.IsDBNull(reader.GetOrdinal("blueprint_node_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("blueprint_node_pk")),
                NodeId = reader.IsDBNull(reader.GetOrdinal("node_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("node_id")),
                NodeKind = reader.IsDBNull(reader.GetOrdinal("node_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("node_kind")),
                Altitude = reader.IsDBNull(reader.GetOrdinal("altitude")) ? (string?)null : reader.GetString(reader.GetOrdinal("altitude")),
                ProjectionOrdinal = reader.IsDBNull(reader.GetOrdinal("projection_ordinal")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("projection_ordinal")),
                NodePortDefinitionPk = reader.IsDBNull(reader.GetOrdinal("node_port_definition_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("node_port_definition_pk")),
                ExpectedSemanticKind = reader.IsDBNull(reader.GetOrdinal("expected_semantic_kind")) ? (string?)null : reader.GetString(reader.GetOrdinal("expected_semantic_kind")),
                ProviderSlotPk = reader.IsDBNull(reader.GetOrdinal("provider_slot_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("provider_slot_pk")),
                SlotId = reader.IsDBNull(reader.GetOrdinal("slot_id")) ? (string?)null : reader.GetString(reader.GetOrdinal("slot_id")),
                SlotPortRequirementPk = reader.IsDBNull(reader.GetOrdinal("slot_port_requirement_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("slot_port_requirement_pk")),
                PortVersionPk = reader.IsDBNull(reader.GetOrdinal("port_version_pk")) ? (long?)null : reader.GetInt64(reader.GetOrdinal("port_version_pk")),
                RequirementOrdinal = reader.IsDBNull(reader.GetOrdinal("requirement_ordinal")) ? (int?)null : reader.GetInt32(reader.GetOrdinal("requirement_ordinal")),
                Role = reader.IsDBNull(reader.GetOrdinal("role")) ? (string?)null : reader.GetString(reader.GetOrdinal("role"))
            };
        }
    }
}

