//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'AssessmentDefinitionInput.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class AssessmentDefinitionInput
    {
        public long AssessmentPk { get; set; }
        public string Role { get; set; } = default!;
        public long SemanticObjectDefinitionPk { get; set; }
    }
}