//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'BlueprintBoundedReturn.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class BlueprintBoundedReturn
    {
        public string CanonicalPointer { get; set; } = default!;
        public byte[]? CanonicalPointerKey { get; set; }
        public long OwnerDefinitionPk { get; set; }
        public long AuthorityDefinitionPk { get; set; }
        public long BlueprintEdgePk { get; set; }
        public long DeclaredBoundContentPk { get; set; }
        public string ReturnKind { get; set; } = default!;
    }
}