//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'EstateSnapshot.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class EstateSnapshot
    {
        public DateTime? CapturedAt { get; set; }
        public byte[] EstateManifestDigest { get; set; } = default!;
        public long EstateSnapshotPk { get; set; }
        public byte[] SnapshotDigest { get; set; } = default!;
        public string? SourceHead { get; set; }
    }
}