//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ExecutionAuthority.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ExecutionAuthority
    {
        public string ExecutionAuthorityId { get; set; } = default!;
        public long ExecutionAuthorityPk { get; set; }
        public long NamespacePk { get; set; }
        public string ObjectKind { get; set; } = default!;
        public long SemanticObjectPk { get; set; }
    }
}