//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'NamespaceMapping.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class NamespaceMapping
    {
        public long MappingRulePk { get; set; }
        public long NamespacePk { get; set; }
        public string ObjectKind { get; set; } = default!;
        public string SourceScope { get; set; } = default!;
    }
}