//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'OperationPortInvocation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class OperationPortInvocation
    {
        public string CanonicalPointer { get; set; } = default!;
        public byte[]? CanonicalPointerKey { get; set; }
        public long OwnerDefinitionPk { get; set; }
        public long ExecutionOperationPk { get; set; }
        public string OperationKind { get; set; } = default!;
        public long PortVersionPk { get; set; }
    }
}