//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Product.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class Product
    {
        public long NamespacePk { get; set; }
        public string ObjectKind { get; set; } = default!;
        public string ProductId { get; set; } = default!;
        public long ProductPk { get; set; }
        public long SemanticObjectPk { get; set; }
    }
}