//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'ProofObligation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class ProofObligation
    {
        public string CanonicalPointer { get; set; } = default!;
        public byte[]? CanonicalPointerKey { get; set; }
        public long OwnerDefinitionPk { get; set; }
        public byte[] DefinitionDigest { get; set; } = default!;
        public long NamespacePk { get; set; }
        public string ObjectKind { get; set; } = default!;
        public string ObligationKind { get; set; } = default!;
        public long OwnerDefinitionPk2 { get; set; }
        public string ProofObligationId { get; set; } = default!;
        public long ProofObligationPk { get; set; }
        public long SemanticObjectDefinitionPk { get; set; }
        public long SemanticObjectPk { get; set; }
        public string? Statement { get; set; }
    }
}