//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'RelationshipObservation.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class RelationshipObservation
    {
        public byte[]? DeclaredTargetDigest { get; set; }
        public string ObservationKind { get; set; } = default!;
        public string RelationshipKind { get; set; } = default!;
        public long SourceObservationPk { get; set; }
        public string? SourceReference { get; set; }
        public string? TargetReference { get; set; }
    }
}