//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'SlotPortRequirement.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class SlotPortRequirement
    {
        public string CanonicalPointer { get; set; } = default!;
        public byte[]? CanonicalPointerKey { get; set; }
        public long OwnerDefinitionPk { get; set; }
        public int Ordinal { get; set; }
        public long PortVersionPk { get; set; }
        public long ProviderSlotPk { get; set; }
        public string? Role { get; set; }
        public long SlotPortRequirementPk { get; set; }
    }
}