//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'SourceAppearance.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class SourceAppearance
    {
        public byte[] AppearanceDigest { get; set; } = default!;
        public byte[]? CapsuleDigest { get; set; }
        public string? ContainerLocator { get; set; }
        public long ContentObjectPk { get; set; }
        public string? EntryId { get; set; }
        public long EstateSnapshotPk { get; set; }
        public byte[]? ReferencedAuthorityDigest { get; set; }
        public long SourceAppearancePk { get; set; }
        public string SourceClass { get; set; } = default!;
        public string SourcePath { get; set; } = default!;
    }
}