//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'UiCrosswalkDefinition.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.DAL.Models
{
    public partial class UiCrosswalkDefinition
    {
        public string CrosswalkId { get; set; } = default!;
        public string? Digest { get; set; }
        public string? DocumentJson { get; set; }
        public DateTime PublishedAt { get; set; }
    }
}