//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'Run.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.Identity.DAL.Models
{
    public partial class Run
    {
        public DateTimeOffset AdmittedAt { get; set; }
        public string CapabilityId { get; set; } = default!;
        public string NamespaceId { get; set; } = default!;
        public Guid PrincipalId { get; set; }
        public string RunId { get; set; } = default!;
        public Guid SessionId { get; set; }
        public string WriterId { get; set; } = default!;
    }
}