//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codelightly.
//     Changes to this file may be overwritten when regenerating code.
//
//     For customizations, use the 'RunCompletion.Custom.cs' file instead.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SFX.Identity.DAL.Models
{
    public partial class RunCompletion
    {
        public DateTimeOffset CompletedAt { get; set; }
        public string? GraphJson { get; set; }
        public long LatestCursor { get; set; }
        public byte[] MaterialDigest { get; set; } = default!;
        public string? OutputJson { get; set; }
        public string RunId { get; set; } = default!;
        public string RunJson { get; set; } = default!;
        public bool TraceComplete { get; set; }
    }
}